# SOME DESCRIPTIVE TITLE.
# Copyright (C) YEAR THE PACKAGE'S COPYRIGHT HOLDER
# This file is distributed under the same license as the PACKAGE package.
# FIRST AUTHOR <EMAIL@ADDRESS>, YEAR.
# 
# Translators:
# Adriaan de Groot <groot@kde.org>, 2020
# Andreas Eitel <github-aneitel@online.de>, 2023
# Gustav Gyges, 2023
# 
#, fuzzy
msgid ""
msgstr ""
"Project-Id-Version: PACKAGE VERSION\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2023-09-28 22:49+0200\n"
"PO-Revision-Date: 2017-08-09 10:34+0000\n"
"Last-Translator: Gustav Gyges, 2023\n"
"Language-Team: German (https://app.transifex.com/calamares/teams/20061/de/)\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Language: de\n"
"Plural-Forms: nplurals=2; plural=(n != 1);\n"

#: src/modules/bootloader/main.py:46
msgid "Install bootloader."
msgstr "Installiere Bootloader."

#: src/modules/bootloader/main.py:644
msgid "Failed to install grub, no partitions defined in global storage"
msgstr ""
"Grub konnte nicht installiert werden, keine Partitionen im globalen Speicher"
" definiert."

#: src/modules/bootloader/main.py:899
msgid "Bootloader installation error"
msgstr "Fehler beim Installieren des Bootloaders"

#: src/modules/bootloader/main.py:900
msgid ""
"The bootloader could not be installed. The installation command "
"<pre>{!s}</pre> returned error code {!s}."
msgstr ""
"Der Bootloader konnte nicht installiert werden. Der Installationsbefehl "
"<pre>{!s}</pre> erzeugte Fehlercode {!s}."

#: src/modules/displaymanager/main.py:509
msgid "Cannot write LXDM configuration file"
msgstr "Schreiben der LXDM-Konfigurationsdatei nicht möglich"

#: src/modules/displaymanager/main.py:510
msgid "LXDM config file {!s} does not exist"
msgstr "LXDM-Konfigurationsdatei {!s} existiert nicht"

#: src/modules/displaymanager/main.py:598
msgid "Cannot write LightDM configuration file"
msgstr "Schreiben der LightDM-Konfigurationsdatei nicht möglich"

#: src/modules/displaymanager/main.py:599
msgid "LightDM config file {!s} does not exist"
msgstr "LightDM-Konfigurationsdatei {!s} existiert nicht"

#: src/modules/displaymanager/main.py:684
msgid "Cannot configure LightDM"
msgstr "Konfiguration von LightDM ist nicht möglich"

#: src/modules/displaymanager/main.py:685
msgid "No LightDM greeter installed."
msgstr "Keine Benutzeroberfläche für LightDM installiert."

#: src/modules/displaymanager/main.py:716
msgid "Cannot write SLIM configuration file"
msgstr "Schreiben der SLIM-Konfigurationsdatei nicht möglich"

#: src/modules/displaymanager/main.py:717
msgid "SLIM config file {!s} does not exist"
msgstr "SLIM-Konfigurationsdatei {!s} existiert nicht"

#: src/modules/displaymanager/main.py:935
msgid "No display managers selected for the displaymanager module."
msgstr "Keine Displaymanager für das Displaymanager-Modul ausgewählt."

#: src/modules/displaymanager/main.py:936
msgid ""
"The displaymanagers list is empty or undefined in both globalstorage and "
"displaymanager.conf."
msgstr ""
"Die Liste der Displaymanager ist leer oder weder in globalstorage noch in "
"displaymanager.conf definiert."

#: src/modules/displaymanager/main.py:1023
msgid "Display manager configuration was incomplete"
msgstr "Die Konfiguration des Displaymanager war unvollständig."

#: src/modules/dracut/main.py:29
msgid "Creating initramfs with dracut."
msgstr "Erstelle initramfs mit dracut."

#: src/modules/dracut/main.py:63
msgid "Failed to run dracut"
msgstr "Dracut konnte nicht ausgeführt werden"

#: src/modules/dracut/main.py:64
#, python-brace-format
msgid "Dracut failed to run on the target with return code: {return_code}"
msgstr ""
"Dracut konnte auf dem System nicht ausgeführt werden, folgender Rückgabecode"
" wurde ausgegeben: {return_code}"

#: src/modules/dummypython/main.py:35
msgid "Dummy python job."
msgstr "Dummy Python-Job"

#: src/modules/dummypython/main.py:37 src/modules/dummypython/main.py:93
#: src/modules/dummypython/main.py:94
msgid "Dummy python step {}"
msgstr "Dummy Python-Schritt {}"

#: src/modules/fstab/main.py:28
msgid "Writing fstab."
msgstr "Schreibe fstab."

#: src/modules/fstab/main.py:377 src/modules/fstab/main.py:383
#: src/modules/fstab/main.py:411 src/modules/initcpiocfg/main.py:256
#: src/modules/initcpiocfg/main.py:260 src/modules/initramfscfg/main.py:85
#: src/modules/initramfscfg/main.py:89 src/modules/localecfg/main.py:140
#: src/modules/mount/main.py:329 src/modules/networkcfg/main.py:105
#: src/modules/openrcdmcryptcfg/main.py:72
#: src/modules/openrcdmcryptcfg/main.py:76 src/modules/rawfs/main.py:164
msgid "Configuration Error"
msgstr "Konfigurationsfehler"

#: src/modules/fstab/main.py:378 src/modules/initramfscfg/main.py:86
#: src/modules/mount/main.py:330 src/modules/openrcdmcryptcfg/main.py:73
#: src/modules/rawfs/main.py:165
msgid "No partitions are defined for <pre>{!s}</pre> to use."
msgstr "Für <pre>{!s}</pre> sind keine zu verwendenden Partitionen definiert."

#: src/modules/fstab/main.py:384 src/modules/initramfscfg/main.py:90
#: src/modules/localecfg/main.py:141 src/modules/networkcfg/main.py:106
#: src/modules/openrcdmcryptcfg/main.py:77
msgid "No root mount point is given for <pre>{!s}</pre> to use."
msgstr ""
"Für <pre>{!s}</pre> wurde kein Einhängepunkt für die Root-Partition "
"angegeben."

#: src/modules/fstab/main.py:412
msgid "No <pre>{!s}</pre> configuration is given for <pre>{!s}</pre> to use."
msgstr ""
"Keine <pre>{!s}</pre> Konfiguration gegeben die <pre>{!s}</pre> benutzen "
"könnte."

#: src/modules/grubcfg/main.py:29
msgid "Configure GRUB."
msgstr "GRUB konfigurieren."

#: src/modules/hwclock/main.py:26
msgid "Setting hardware clock."
msgstr "Einstellen der Hardware-Uhr."

#: src/modules/initcpiocfg/main.py:27
msgid "Configuring mkinitcpio."
msgstr "Konfiguriere mkinitcpio. "

#: src/modules/initcpiocfg/main.py:257
msgid "No partitions are defined for <pre>initcpiocfg</pre>."
msgstr "Es sind keine Partitionen definiert für <pre>initcpiocfg</pre>."

#: src/modules/initcpiocfg/main.py:261
msgid "No root mount point for <pre>initcpiocfg</pre>."
msgstr "Kein Root-Einhängepunkt für <pre>initcpiocfg</pre>."

#: src/modules/initramfscfg/main.py:32
msgid "Configuring initramfs."
msgstr "Konfiguriere initramfs."

#: src/modules/localecfg/main.py:31
msgid "Configuring locales."
msgstr "Konfiguriere Lokalisierungen."

#: src/modules/mkinitfs/main.py:27
msgid "Creating initramfs with mkinitfs."
msgstr "Erstelle initramfs mit mkinitfs."

#: src/modules/mkinitfs/main.py:49
msgid "Failed to run mkinitfs on the target"
msgstr "Ausführung von mkinitfs auf dem Ziel fehlgeschlagen."

#: src/modules/mkinitfs/main.py:50
msgid "The exit code was {}"
msgstr "Der Exit-Code war {}"

#: src/modules/mount/main.py:43
msgid "Mounting partitions."
msgstr "Hänge Partitionen ein."

#: src/modules/mount/main.py:164 src/modules/mount/main.py:200
msgid "Internal error mounting zfs datasets"
msgstr "Interner Fehler beim Einhängen des ZFS-Datensets"

#: src/modules/mount/main.py:176
msgid "Failed to import zpool"
msgstr "Zpool konnte nicht importiert werden"

#: src/modules/mount/main.py:192
msgid "Failed to unlock zpool"
msgstr "Zpool konnte nicht entsperrt werden"

#: src/modules/mount/main.py:209 src/modules/mount/main.py:214
msgid "Failed to set zfs mountpoint"
msgstr "Zpool-Einhängepunkt konnte nicht gesetzt werden"

#: src/modules/mount/main.py:365
msgid "zfs mounting error"
msgstr "Fehler beim Einhängen von ZFS"

#: src/modules/networkcfg/main.py:29
msgid "Saving network configuration."
msgstr "Speichere Netzwerkkonfiguration."

#: src/modules/openrcdmcryptcfg/main.py:26
msgid "Configuring OpenRC dmcrypt service."
msgstr "Konfiguriere den dmcrypt-Dienst von OpenRC."

#: src/modules/packages/main.py:54 src/modules/packages/main.py:65
#: src/modules/packages/main.py:75
msgid "Install packages."
msgstr "Pakete installieren "

#: src/modules/packages/main.py:63
#, python-format
msgid "Processing packages (%(count)d / %(total)d)"
msgstr "Verarbeite Pakete (%(count)d / %(total)d)"

#: src/modules/packages/main.py:68
#, python-format
msgid "Installing one package."
msgid_plural "Installing %(num)d packages."
msgstr[0] "Installiere ein Paket"
msgstr[1] "Installiere %(num)d Pakete."

#: src/modules/packages/main.py:71
#, python-format
msgid "Removing one package."
msgid_plural "Removing %(num)d packages."
msgstr[0] "Entferne ein Paket"
msgstr[1] "Entferne %(num)d Pakete."

#: src/modules/packages/main.py:740 src/modules/packages/main.py:752
#: src/modules/packages/main.py:780
msgid "Package Manager error"
msgstr "Fehler im Paketmanager"

#: src/modules/packages/main.py:741
msgid ""
"The package manager could not prepare updates. The command <pre>{!s}</pre> "
"returned error code {!s}."
msgstr ""
"Der Paketmanager konnte die Aktualisierungen nicht vorbereiten. Der Befehl "
"<pre>{!s}</pre> erzeugte Fehlercode {!s}."

#: src/modules/packages/main.py:753
msgid ""
"The package manager could not update the system. The command <pre>{!s}</pre>"
" returned error code {!s}."
msgstr ""
"Der Paketmanager konnte das System nicht aktualisieren. Der Befehl "
"<pre>{!s}</pre> erzeugte Fehlercode {!s}."

#: src/modules/packages/main.py:781
msgid ""
"The package manager could not make changes to the installed system. The "
"command <pre>{!s}</pre> returned error code {!s}."
msgstr ""
"Der Paketmanager konnte das installierte System nicht verändern. Der Befehl "
"<pre>{!s}</pre> erzeugte Fehlercode {!s}."

#: src/modules/plymouthcfg/main.py:27
msgid "Configure Plymouth theme"
msgstr "Konfiguriere Plymouth-Thema"

#: src/modules/rawfs/main.py:26
msgid "Installing data."
msgstr "Installiere Daten."

#: src/modules/services-openrc/main.py:29
msgid "Configure OpenRC services"
msgstr "Konfiguriere OpenRC-Dienste"

#: src/modules/services-openrc/main.py:57
msgid "Cannot add service {name!s} to run-level {level!s}."
msgstr "Kann den Dienst {name!s} nicht zu Runlevel {level!s} hinzufügen."

#: src/modules/services-openrc/main.py:59
msgid "Cannot remove service {name!s} from run-level {level!s}."
msgstr "Kann den Dienst {name!s} nicht aus Runlevel {level!s} entfernen."

#: src/modules/services-openrc/main.py:61
msgid ""
"Unknown service-action <code>{arg!s}</code> for service {name!s} in run-"
"level {level!s}."
msgstr ""
"Unbekannte Aktion <code>{arg!s}</code> für Dienst {name!s} in Runlevel "
"{level!s}."

#: src/modules/services-openrc/main.py:93
msgid "Cannot modify service"
msgstr "Der Dienst kann nicht geändert werden."

#: src/modules/services-openrc/main.py:94
msgid ""
"<code>rc-update {arg!s}</code> call in chroot returned error code {num!s}."
msgstr ""
"<code>rc-update {arg!s}</code> Aufruf in chroot lieferte Fehlercode {num!s} "
"zurück."

#: src/modules/services-openrc/main.py:101
msgid "Target runlevel does not exist"
msgstr "Vorgesehenes Runlevel existiert nicht"

#: src/modules/services-openrc/main.py:102
msgid ""
"The path for runlevel {level!s} is <code>{path!s}</code>, which does not "
"exist."
msgstr ""
"Der Pfad für Runlevel {level!s} ist <code>{path!s}</code>, welcher nicht "
"existiert."

#: src/modules/services-openrc/main.py:110
msgid "Target service does not exist"
msgstr "Der vorgesehene Dienst existiert nicht"

#: src/modules/services-openrc/main.py:111
msgid ""
"The path for service {name!s} is <code>{path!s}</code>, which does not "
"exist."
msgstr ""
"Der Pfad für den Dienst {name!s} is <code>{path!s}</code>, welcher nicht "
"existiert."

#: src/modules/services-systemd/main.py:26
msgid "Configure systemd units"
msgstr "systemd-Einheiten konfigurieren"

#: src/modules/services-systemd/main.py:64
msgid "Cannot modify unit"
msgstr "Unit kann nicht geändert werden"

#: src/modules/services-systemd/main.py:65
msgid ""
"<code>systemctl {_action!s}</code> call in chroot returned error code "
"{_exit_code!s}."
msgstr ""
"<code>systemctl {_action!s}</code> Aufruf in chroot gab Fehlercode "
"{_exit_code!s} zurück."

#: src/modules/services-systemd/main.py:66
msgid "Cannot {_action!s} systemd unit <code>{_name!s}</code>."
msgstr "Kann {_action!s} systemd-Unit <code>{_name!s}</code>nicht ausführen."

#: src/modules/unpackfs/main.py:34
msgid "Filling up filesystems."
msgstr "Befüllen von Dateisystemen."

#: src/modules/unpackfs/main.py:254
msgid "rsync failed with error code {}."
msgstr "rsync fehlgeschlagen mit Fehlercode {}."

#: src/modules/unpackfs/main.py:299
msgid "Unpacking image {}/{}, file {}/{}"
msgstr "Abbilddatei Entpacken {}/{}, Datei {}/{}"

#: src/modules/unpackfs/main.py:314
msgid "Starting to unpack {}"
msgstr "Beginn des Entpackens {}"

#: src/modules/unpackfs/main.py:323 src/modules/unpackfs/main.py:467
msgid "Failed to unpack image \"{}\""
msgstr "Entpacken der Abbilddatei \"{}\" fehlgeschlagen"

#: src/modules/unpackfs/main.py:430
msgid "No mount point for root partition"
msgstr "Kein Einhängepunkt für die Root-Partition"

#: src/modules/unpackfs/main.py:431
msgid "globalstorage does not contain a \"rootMountPoint\" key."
msgstr "Globalstorage enthält keinen Schlüssel für \"rootMountPoint\"."

#: src/modules/unpackfs/main.py:434
msgid "Bad mount point for root partition"
msgstr "Ungültiger Einhängepunkt für die Root-Partition"

#: src/modules/unpackfs/main.py:435
msgid "rootMountPoint is \"{}\", which does not exist."
msgstr "rootMountPoint ist \"{}\", was nicht existiert."

#: src/modules/unpackfs/main.py:439 src/modules/unpackfs/main.py:455
#: src/modules/unpackfs/main.py:459 src/modules/unpackfs/main.py:465
#: src/modules/unpackfs/main.py:480
msgid "Bad unpackfs configuration"
msgstr "Fehlerhafte unpackfs-Konfiguration"

#: src/modules/unpackfs/main.py:440
msgid "There is no configuration information."
msgstr "Es gibt keine Informationen zur Konfiguration."

#: src/modules/unpackfs/main.py:456
msgid "The filesystem for \"{}\" ({}) is not supported by your current kernel"
msgstr ""
"Das Dateisystem für \"{}\" ({}) wird von Ihrem aktuellen Kernel nicht "
"unterstützt"

#: src/modules/unpackfs/main.py:460
msgid "The source filesystem \"{}\" does not exist"
msgstr "Das Quelldateisystem \"{}\" existiert nicht"

#: src/modules/unpackfs/main.py:466
msgid ""
"Failed to find unsquashfs, make sure you have the squashfs-tools package "
"installed."
msgstr ""
"Unsquashfs nicht gefunden, stellen Sie sicher, dass das Paket squashfs-tools"
" installiert ist."

#: src/modules/unpackfs/main.py:481
msgid "The destination \"{}\" in the target system is not a directory"
msgstr "Das Ziel \"{}\" im Zielsystem ist kein Verzeichnis"

#: src/modules/zfshostid/main.py:27
msgid "Copying zfs generated hostid."
msgstr "Kopieren der von ZFS generierten hostid."
