# SOME DESCRIPTIVE TITLE.
# Copyright (C) YEAR THE PACKAGE'S COPYRIGHT HOLDER
# This file is distributed under the same license as the PACKAGE package.
# FIRST AUTHOR <EMAIL@ADDRESS>, YEAR.
# 
# Translators:
# HelaBasa Group <transifex-helabasa-group@yalu.lk>, 2021
# Sandaruwan Samaraweera, 2022
# 
#, fuzzy
msgid ""
msgstr ""
"Project-Id-Version: PACKAGE VERSION\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2023-09-28 22:49+0200\n"
"PO-Revision-Date: 2017-08-09 10:34+0000\n"
"Last-Translator: Sandaruwan Samaraweera, 2022\n"
"Language-Team: Sinhala (https://app.transifex.com/calamares/teams/20061/si/)\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Language: si\n"
"Plural-Forms: nplurals=2; plural=(n != 1);\n"

#: src/modules/bootloader/main.py:46
msgid "Install bootloader."
msgstr "bootloader ස්ථාපනය කරන්න."

#: src/modules/bootloader/main.py:644
msgid "Failed to install grub, no partitions defined in global storage"
msgstr ""
"Grub ස්ථාපනය කිරීමට අපොහොසත් විය, ගෝලීය ආචයනය තුළ කොටස් අර්ථ දක්වා නොමැත"

#: src/modules/bootloader/main.py:899
msgid "Bootloader installation error"
msgstr "Bootloader ස්ථාපනය කිරීමේ දෝෂයකි"

#: src/modules/bootloader/main.py:900
msgid ""
"The bootloader could not be installed. The installation command "
"<pre>{!s}</pre> returned error code {!s}."
msgstr ""
"ඇරඹුම් කාරකය ස්ථාපනය කල නොහැක. ස්ථාපන විධානය <pre>{!s}</pre> දෝෂ කේතය {!s} "
"ලබා දුන්නේය."

#: src/modules/displaymanager/main.py:509
msgid "Cannot write LXDM configuration file"
msgstr "LXDM වින්‍යාස ගොනුව ලිවිය නොහැක"

#: src/modules/displaymanager/main.py:510
msgid "LXDM config file {!s} does not exist"
msgstr "LXDM වින්‍යාස ගොනුව {!s} නොපවතී"

#: src/modules/displaymanager/main.py:598
msgid "Cannot write LightDM configuration file"
msgstr "LightDM වින්‍යාස ගොනුව ලිවිය නොහැක"

#: src/modules/displaymanager/main.py:599
msgid "LightDM config file {!s} does not exist"
msgstr "LightDM වින්‍යාස ගොනුව {!s} නොපවතී"

#: src/modules/displaymanager/main.py:684
msgid "Cannot configure LightDM"
msgstr "LightDM වින්‍යාස කළ නොහැක"

#: src/modules/displaymanager/main.py:685
msgid "No LightDM greeter installed."
msgstr "LightDM ග්‍රීටර් ස්ථාපනය කර නැත."

#: src/modules/displaymanager/main.py:716
msgid "Cannot write SLIM configuration file"
msgstr "SLIM වින්‍යාස ගොනුව ලිවිය නොහැක"

#: src/modules/displaymanager/main.py:717
msgid "SLIM config file {!s} does not exist"
msgstr "SLIM වින්‍යාස ගොනුව {!s} නොපවතී"

#: src/modules/displaymanager/main.py:935
msgid "No display managers selected for the displaymanager module."
msgstr "සංදර්ශක කළමනාකරු මොඩියුලය සඳහා සංදර්ශක කළමනාකරුවන් තෝරාගෙන නොමැත."

#: src/modules/displaymanager/main.py:936
msgid ""
"The displaymanagers list is empty or undefined in both globalstorage and "
"displaymanager.conf."
msgstr ""
"ගෝලීය ගබඩාව සහ displaymanager.conf යන දෙකෙහිම සංදර්ශක කළමනාකරු ලැයිස්තුව "
"හිස් හෝ අර්ථ දක්වා නොමැත."

#: src/modules/displaymanager/main.py:1023
msgid "Display manager configuration was incomplete"
msgstr "සංදර්ශක කළමනාකරු වින්‍යාසය අසම්පූර්ණ විය"

#: src/modules/dracut/main.py:29
msgid "Creating initramfs with dracut."
msgstr "dracut සමඟ initramfs නිර්මාණය කිරීම."

#: src/modules/dracut/main.py:63
msgid "Failed to run dracut"
msgstr ""

#: src/modules/dracut/main.py:64
#, python-brace-format
msgid "Dracut failed to run on the target with return code: {return_code}"
msgstr ""

#: src/modules/dummypython/main.py:35
msgid "Dummy python job."
msgstr "ඩමි python වැඩසටහන."

#: src/modules/dummypython/main.py:37 src/modules/dummypython/main.py:93
#: src/modules/dummypython/main.py:94
msgid "Dummy python step {}"
msgstr "ව්‍යාජ python පියවර {}"

#: src/modules/fstab/main.py:28
msgid "Writing fstab."
msgstr "fstab ලියමින්."

#: src/modules/fstab/main.py:377 src/modules/fstab/main.py:383
#: src/modules/fstab/main.py:411 src/modules/initcpiocfg/main.py:256
#: src/modules/initcpiocfg/main.py:260 src/modules/initramfscfg/main.py:85
#: src/modules/initramfscfg/main.py:89 src/modules/localecfg/main.py:140
#: src/modules/mount/main.py:329 src/modules/networkcfg/main.py:105
#: src/modules/openrcdmcryptcfg/main.py:72
#: src/modules/openrcdmcryptcfg/main.py:76 src/modules/rawfs/main.py:164
msgid "Configuration Error"
msgstr "වින්‍යාස දෝෂය"

#: src/modules/fstab/main.py:378 src/modules/initramfscfg/main.py:86
#: src/modules/mount/main.py:330 src/modules/openrcdmcryptcfg/main.py:73
#: src/modules/rawfs/main.py:165
msgid "No partitions are defined for <pre>{!s}</pre> to use."
msgstr "{!s} සඳහා භාවිතා කිරීමට කිසිදු කොටස් නිර්වචනය කර නොමැත."

#: src/modules/fstab/main.py:384 src/modules/initramfscfg/main.py:90
#: src/modules/localecfg/main.py:141 src/modules/networkcfg/main.py:106
#: src/modules/openrcdmcryptcfg/main.py:77
msgid "No root mount point is given for <pre>{!s}</pre> to use."
msgstr "{!s} සඳහා භාවිතා කිරීමට root mount point ලබා දී නොමැත."

#: src/modules/fstab/main.py:412
msgid "No <pre>{!s}</pre> configuration is given for <pre>{!s}</pre> to use."
msgstr ""
"භාවිතා කිරීමට <pre>{!s}</pre> සඳහා <pre>{!s}</pre> වින්‍යාසයක් ලබා දී නොමැත."

#: src/modules/grubcfg/main.py:29
msgid "Configure GRUB."
msgstr "GRUB වින්‍යාස කරන්න."

#: src/modules/hwclock/main.py:26
msgid "Setting hardware clock."
msgstr "දෘඩාංග ඔරලෝසුව සැකසෙමින්."

#: src/modules/initcpiocfg/main.py:27
msgid "Configuring mkinitcpio."
msgstr "mkinitcpio වින්‍යාස කරමින්."

#: src/modules/initcpiocfg/main.py:257
msgid "No partitions are defined for <pre>initcpiocfg</pre>."
msgstr ""

#: src/modules/initcpiocfg/main.py:261
msgid "No root mount point for <pre>initcpiocfg</pre>."
msgstr ""

#: src/modules/initramfscfg/main.py:32
msgid "Configuring initramfs."
msgstr "initramfs වින්‍යාස කිරීම."

#: src/modules/localecfg/main.py:31
msgid "Configuring locales."
msgstr "ස්ථාන වින්‍යාස කිරීම."

#: src/modules/mkinitfs/main.py:27
msgid "Creating initramfs with mkinitfs."
msgstr "mkinitfs සමඟ initramfs නිර්මාණය කිරීම."

#: src/modules/mkinitfs/main.py:49
msgid "Failed to run mkinitfs on the target"
msgstr "ඉලක්කය මත mkinitfs ධාවනය කිරීමට අසමත් විය"

#: src/modules/mkinitfs/main.py:50
msgid "The exit code was {}"
msgstr "පිටවීමේ කේතය වූයේ {}"

#: src/modules/mount/main.py:43
msgid "Mounting partitions."
msgstr "කොටස් සවි කිරීම."

#: src/modules/mount/main.py:164 src/modules/mount/main.py:200
msgid "Internal error mounting zfs datasets"
msgstr "zfs දත්ත කට්ටල සවිකිරීමේ අභ්‍යන්තර දෝෂයකි"

#: src/modules/mount/main.py:176
msgid "Failed to import zpool"
msgstr "zpool ආයාත කිරීමට අසමත් විය"

#: src/modules/mount/main.py:192
msgid "Failed to unlock zpool"
msgstr "zpool අගුලු හැරීමට අසමත් විය"

#: src/modules/mount/main.py:209 src/modules/mount/main.py:214
msgid "Failed to set zfs mountpoint"
msgstr "zfs සවිකිරීමේ ලක්ෂ්‍යය සැකසීමට අසමත් විය"

#: src/modules/mount/main.py:365
msgid "zfs mounting error"
msgstr "zfs සවිකිරීමේ දෝෂයකි"

#: src/modules/networkcfg/main.py:29
msgid "Saving network configuration."
msgstr "ජාල වින්‍යාසය සුරැකෙමින්."

#: src/modules/openrcdmcryptcfg/main.py:26
msgid "Configuring OpenRC dmcrypt service."
msgstr "OpenRC dmcrypt සේවාව වින්‍යාස කරමින්."

#: src/modules/packages/main.py:54 src/modules/packages/main.py:65
#: src/modules/packages/main.py:75
msgid "Install packages."
msgstr "ඇසුරුම් ස්ථාපනය කරන්න."

#: src/modules/packages/main.py:63
#, python-format
msgid "Processing packages (%(count)d / %(total)d)"
msgstr "පැකේජ සැකසීම (%(count)d / %(total)d)"

#: src/modules/packages/main.py:68
#, python-format
msgid "Installing one package."
msgid_plural "Installing %(num)d packages."
msgstr[0] "ඇසුරුමක් ස්ථාපනය වෙමින්."
msgstr[1] "ඇසුරුම් %(num)d ක් ස්ථාපනය වෙමින්."

#: src/modules/packages/main.py:71
#, python-format
msgid "Removing one package."
msgid_plural "Removing %(num)d packages."
msgstr[0] "ඇසුරුමක් ඉවත් වෙමින්."
msgstr[1] "ඇසුරුම් %(num)d ක් ඉවත් වෙමින්."

#: src/modules/packages/main.py:740 src/modules/packages/main.py:752
#: src/modules/packages/main.py:780
msgid "Package Manager error"
msgstr "පැකේජ කළමනාකරු දෝෂයකි"

#: src/modules/packages/main.py:741
msgid ""
"The package manager could not prepare updates. The command <pre>{!s}</pre> "
"returned error code {!s}."
msgstr ""
"පැකේජ කළමනාකරුට යාවත්කාලීන සකස් කිරීමට නොහැකි විය. විධානය <pre>{!s}</pre> "
"දෝෂ කේතය {!s} ලබා දුන්නේය."

#: src/modules/packages/main.py:753
msgid ""
"The package manager could not update the system. The command <pre>{!s}</pre>"
" returned error code {!s}."
msgstr ""
"පැකේජ කළමනාකරුට පද්ධතිය යාවත්කාලීන කළ නොහැකි විය. විධානය <pre>{!s}</pre> දෝෂ"
" කේතය {!s} ලබා දුන්නේය."

#: src/modules/packages/main.py:781
msgid ""
"The package manager could not make changes to the installed system. The "
"command <pre>{!s}</pre> returned error code {!s}."
msgstr ""
"පැකේජ කළමනාකරුට ස්ථාපිත පද්ධතියට වෙනස්කම් සිදු කළ නොහැක. විධානය "
"<pre>{!s}</pre> දෝෂ කේතය {!s} ලබා දුන්නේය."

#: src/modules/plymouthcfg/main.py:27
msgid "Configure Plymouth theme"
msgstr "Plymouth තේමාව වින්‍යාස කරන්න"

#: src/modules/rawfs/main.py:26
msgid "Installing data."
msgstr "දත්ත ස්ථාපනය වෙමින්."

#: src/modules/services-openrc/main.py:29
msgid "Configure OpenRC services"
msgstr "OpenRC සේවා වින්‍යාස කරන්න"

#: src/modules/services-openrc/main.py:57
msgid "Cannot add service {name!s} to run-level {level!s}."
msgstr "ධාවන මට්ටම {level!s} වෙත සේවාව {name!s} එක් කළ නොහැක."

#: src/modules/services-openrc/main.py:59
msgid "Cannot remove service {name!s} from run-level {level!s}."
msgstr "ධාවන මට්ටමේ {level!s} වෙතින් සේවාව {name!s} ඉවත් කළ නොහැක."

#: src/modules/services-openrc/main.py:61
msgid ""
"Unknown service-action <code>{arg!s}</code> for service {name!s} in run-"
"level {level!s}."
msgstr ""
"{name!s} සේවාව සඳහා නොදන්නා සේවා-ක්‍රියාව <code>{arg!s}</code> ධාවන මට්ටමේ "
"{level!s}."

#: src/modules/services-openrc/main.py:93
msgid "Cannot modify service"
msgstr "සේවාව වෙනස් කළ නොහැක"

#: src/modules/services-openrc/main.py:94
msgid ""
"<code>rc-update {arg!s}</code> call in chroot returned error code {num!s}."
msgstr ""
"<code>rc-update {arg!s}</code> chroot හි ඇමතුම {num!s} දෝෂ කේතය ලබා දුන්නේය."

#: src/modules/services-openrc/main.py:101
msgid "Target runlevel does not exist"
msgstr "ඉලක්ක ධාවන මට්ටම නොපවතී"

#: src/modules/services-openrc/main.py:102
msgid ""
"The path for runlevel {level!s} is <code>{path!s}</code>, which does not "
"exist."
msgstr "ධාවන මට්ටම {level!s} සඳහා මාර්ගය <code>{path!s}</code>, එය නොපවතී."

#: src/modules/services-openrc/main.py:110
msgid "Target service does not exist"
msgstr "ඉලක්ක සේවාව නොපවතී"

#: src/modules/services-openrc/main.py:111
msgid ""
"The path for service {name!s} is <code>{path!s}</code>, which does not "
"exist."
msgstr "සේවාව සඳහා {name!s} මාර්ගය <code>{path!s}</code>, එය නොපවතී."

#: src/modules/services-systemd/main.py:26
msgid "Configure systemd units"
msgstr ""

#: src/modules/services-systemd/main.py:64
msgid "Cannot modify unit"
msgstr ""

#: src/modules/services-systemd/main.py:65
msgid ""
"<code>systemctl {_action!s}</code> call in chroot returned error code "
"{_exit_code!s}."
msgstr ""

#: src/modules/services-systemd/main.py:66
msgid "Cannot {_action!s} systemd unit <code>{_name!s}</code>."
msgstr ""

#: src/modules/unpackfs/main.py:34
msgid "Filling up filesystems."
msgstr "ගොනු පද්ධති පිරවීම."

#: src/modules/unpackfs/main.py:254
msgid "rsync failed with error code {}."
msgstr "දෝෂ කේතය {} සමඟ rsync අසාර්ථක විය."

#: src/modules/unpackfs/main.py:299
msgid "Unpacking image {}/{}, file {}/{}"
msgstr "රූපය {}/{}, ගොනුව {}/{} අසුරමින්"

#: src/modules/unpackfs/main.py:314
msgid "Starting to unpack {}"
msgstr "ඉවත් කිරීමට පටන් ගනියි {}"

#: src/modules/unpackfs/main.py:323 src/modules/unpackfs/main.py:467
msgid "Failed to unpack image \"{}\""
msgstr "\"{}\" රූපය ඉවත් කිරීමට අසමත් විය"

#: src/modules/unpackfs/main.py:430
msgid "No mount point for root partition"
msgstr "root කොටස සඳහා සවි කිරීමේ ලක්ෂ්‍යයක් නොමැත"

#: src/modules/unpackfs/main.py:431
msgid "globalstorage does not contain a \"rootMountPoint\" key."
msgstr "ගෝලීය ගබඩාවේ \"rootMountPoint\" යතුරක් අඩංගු නොවේ."

#: src/modules/unpackfs/main.py:434
msgid "Bad mount point for root partition"
msgstr "මූල කොටස සඳහා නරක සවි කිරීමේ ලක්ෂ්‍යය"

#: src/modules/unpackfs/main.py:435
msgid "rootMountPoint is \"{}\", which does not exist."
msgstr "rootMountPoint යනු \"{}\", එය නොපවතී."

#: src/modules/unpackfs/main.py:439 src/modules/unpackfs/main.py:455
#: src/modules/unpackfs/main.py:459 src/modules/unpackfs/main.py:465
#: src/modules/unpackfs/main.py:480
msgid "Bad unpackfs configuration"
msgstr "වැරදි unpackfs වින්‍යාසය"

#: src/modules/unpackfs/main.py:440
msgid "There is no configuration information."
msgstr "වින්‍යාස තොරතුරු නොමැත."

#: src/modules/unpackfs/main.py:456
msgid "The filesystem for \"{}\" ({}) is not supported by your current kernel"
msgstr "\"{}\" ({}) සඳහා ගොනු පද්ධතිය ඔබගේ වත්මන් කර්නලයෙන් සහය නොදක්වයි"

#: src/modules/unpackfs/main.py:460
msgid "The source filesystem \"{}\" does not exist"
msgstr "මූලාශ්‍ර ගොනු පද්ධතිය \"{}\" නොපවතී"

#: src/modules/unpackfs/main.py:466
msgid ""
"Failed to find unsquashfs, make sure you have the squashfs-tools package "
"installed."
msgstr ""
"Unsquashfs සොයා ගැනීමට අපොහොසත් විය, ඔබ squashfs-tools පැකේජය ස්ථාපනය කර ඇති"
" බවට වග බලා ගන්න."

#: src/modules/unpackfs/main.py:481
msgid "The destination \"{}\" in the target system is not a directory"
msgstr "ඉලක්ක පද්ධතියේ \"{}\" ගමනාන්තය නාමාවලියක් නොවේ"

#: src/modules/zfshostid/main.py:27
msgid "Copying zfs generated hostid."
msgstr ""
