# SOME DESCRIPTIVE TITLE.
# Copyright (C) YEAR THE PACKAGE'S COPYRIGHT HOLDER
# This file is distributed under the same license as the PACKAGE package.
# FIRST AUTHOR <EMAIL@ADDRESS>, YEAR.
# 
# Translators:
# Danial Behzadi <dani.behzi@ubuntu.com>, 2020
# alireza jamshidi <alirezajam98@gmail.com>, 2020
# 
#, fuzzy
msgid ""
msgstr ""
"Project-Id-Version: PACKAGE VERSION\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2020-12-07 17:09+0100\n"
"PO-Revision-Date: 2017-08-09 10:34+0000\n"
"Last-Translator: alireza jamshidi <alirezajam98@gmail.com>, 2020\n"
"Language-Team: Persian (https://www.transifex.com/calamares/teams/20061/fa/)\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Language: fa\n"
"Plural-Forms: nplurals=2; plural=(n > 1);\n"

#: src/modules/grubcfg/main.py:28
msgid "Configure GRUB."
msgstr "در حال پیکربندی گراب."

#: src/modules/mount/main.py:30
msgid "Mounting partitions."
msgstr "در حال سوار کردن افرازها."

#: src/modules/mount/main.py:127 src/modules/initcpiocfg/main.py:198
#: src/modules/initcpiocfg/main.py:202
#: src/modules/luksopenswaphookcfg/main.py:86
#: src/modules/luksopenswaphookcfg/main.py:90 src/modules/rawfs/main.py:164
#: src/modules/initramfscfg/main.py:85 src/modules/initramfscfg/main.py:89
#: src/modules/openrcdmcryptcfg/main.py:72
#: src/modules/openrcdmcryptcfg/main.py:76 src/modules/fstab/main.py:361
#: src/modules/fstab/main.py:367 src/modules/localecfg/main.py:135
#: src/modules/networkcfg/main.py:39
msgid "Configuration Error"
msgstr "خطای پیکربندی"

#: src/modules/mount/main.py:128 src/modules/initcpiocfg/main.py:199
#: src/modules/luksopenswaphookcfg/main.py:87 src/modules/rawfs/main.py:165
#: src/modules/initramfscfg/main.py:86 src/modules/openrcdmcryptcfg/main.py:73
#: src/modules/fstab/main.py:362
msgid "No partitions are defined for <pre>{!s}</pre> to use."
msgstr "هیچ افرازی برای استفادهٔ <pre>{!s}</pre> تعریف نشده."

#: src/modules/services-systemd/main.py:26
msgid "Configure systemd services"
msgstr "در حال پیکربندی خدمات سیستم‌دی"

#: src/modules/services-systemd/main.py:59
#: src/modules/services-openrc/main.py:93
msgid "Cannot modify service"
msgstr "نمی‌توان خدمت را دستکاری کرد"

#: src/modules/services-systemd/main.py:60
msgid ""
"<code>systemctl {arg!s}</code> call in chroot returned error code {num!s}."
msgstr ""
"فراخوانی <code>systemctl {arg!s}</code> در chroot رمز خطای {num!s} را "
"برگرداند."

#: src/modules/services-systemd/main.py:63
#: src/modules/services-systemd/main.py:67
msgid "Cannot enable systemd service <code>{name!s}</code>."
msgstr "نمی‌توان خدمت سیستم‌دی <code>{name!s}</code> را به کار انداخت."

#: src/modules/services-systemd/main.py:65
msgid "Cannot enable systemd target <code>{name!s}</code>."
msgstr "نمی‌توان هدف سیستم‌دی <code>{name!s}</code> را به کار انداخت."

#: src/modules/services-systemd/main.py:69
msgid "Cannot disable systemd target <code>{name!s}</code>."
msgstr "نمی‌توان خدمت سیستم‌دی <code>{name!s}</code> را از کار انداخت."

#: src/modules/services-systemd/main.py:71
msgid "Cannot mask systemd unit <code>{name!s}</code>."
msgstr "نمی‌توان واحد سیستم‌دی <code>{name!s}</code> را پوشاند."

#: src/modules/services-systemd/main.py:73
msgid ""
"Unknown systemd commands <code>{command!s}</code> and "
"<code>{suffix!s}</code> for unit {name!s}."
msgstr ""
"دستورات ناشناختهٔ سیستم‌دی <code>{command!s}</code> و "
"<code>{suffix!s}</code> برای واحد {name!s}."

#: src/modules/umount/main.py:31
msgid "Unmount file systems."
msgstr "پیاده کردن سامانه‌های پرونده."

#: src/modules/unpackfs/main.py:35
msgid "Filling up filesystems."
msgstr "در حال پر کردن سامانه‌پرونده‌ها."

#: src/modules/unpackfs/main.py:255
msgid "rsync failed with error code {}."
msgstr "آرسینک با رمز خطای {} شکست خورد."

#: src/modules/unpackfs/main.py:300
msgid "Unpacking image {}/{}, file {}/{}"
msgstr "در حال بسته‌گشایی تصویر {}/{}، پروندهٔ {}/{}"

#: src/modules/unpackfs/main.py:315
msgid "Starting to unpack {}"
msgstr "در حال شروع بسته‌گشایی {}"

#: src/modules/unpackfs/main.py:324 src/modules/unpackfs/main.py:464
msgid "Failed to unpack image \"{}\""
msgstr "شکست در بسته‌گشایی تصویر {}"

#: src/modules/unpackfs/main.py:431
msgid "No mount point for root partition"
msgstr "هیچ نقطهٔ اتّصالی برای افراز ریشه وجود ندارد"

#: src/modules/unpackfs/main.py:432
msgid "globalstorage does not contain a \"rootMountPoint\" key, doing nothing"
msgstr "globalstorage کلید rootMountPoint را ندارد. کاری انجام نمی‌شود"

#: src/modules/unpackfs/main.py:437
msgid "Bad mount point for root partition"
msgstr "نقطهٔ اتّصال بد برای افراز ریشه"

#: src/modules/unpackfs/main.py:438
msgid "rootMountPoint is \"{}\", which does not exist, doing nothing"
msgstr "نقطهٔ اتّصال ریشه {} است که وجود ندارد. کاری انجام نمی‌شود"

#: src/modules/unpackfs/main.py:454 src/modules/unpackfs/main.py:458
#: src/modules/unpackfs/main.py:478
msgid "Bad unsquash configuration"
msgstr "پیکربندی بد unsquash"

#: src/modules/unpackfs/main.py:455
msgid "The filesystem for \"{}\" ({}) is not supported by your current kernel"
msgstr "کرنل کنونیتان از سامانه‌پروندهٔ {} ({}) پشتیبانی نمی‌کند"

#: src/modules/unpackfs/main.py:459
msgid "The source filesystem \"{}\" does not exist"
msgstr "سامانهٔ پروندهٔ مبدأ {} وجود ندارد"

#: src/modules/unpackfs/main.py:465
msgid ""
"Failed to find unsquashfs, make sure you have the squashfs-tools package "
"installed"
msgstr "شکست در یافتن unsquashfs. مطمئن شوید بستهٔ squashfs-tools نصب است"

#: src/modules/unpackfs/main.py:479
msgid "The destination \"{}\" in the target system is not a directory"
msgstr "مقصد {} در سامانهٔ هدف، یک شاخه نیست"

#: src/modules/displaymanager/main.py:514
msgid "Cannot write KDM configuration file"
msgstr "نمی‌توان پروندهٔ پیکربندی KDM را نوشت"

#: src/modules/displaymanager/main.py:515
msgid "KDM config file {!s} does not exist"
msgstr "پروندهٔ پیکربندی {!s} وجود ندارد"

#: src/modules/displaymanager/main.py:576
msgid "Cannot write LXDM configuration file"
msgstr "نمی‌توان پروندهٔ پیکربندی LXDM را نوشت"

#: src/modules/displaymanager/main.py:577
msgid "LXDM config file {!s} does not exist"
msgstr "پروندهٔ پیکربندی {!s} وجود ندارد"

#: src/modules/displaymanager/main.py:660
msgid "Cannot write LightDM configuration file"
msgstr "نمی‌توان پروندهٔ پیکربندی LightDM را نوشت"

#: src/modules/displaymanager/main.py:661
msgid "LightDM config file {!s} does not exist"
msgstr "پروندهٔ پیکربندی {!s} وجود ندارد"

#: src/modules/displaymanager/main.py:735
msgid "Cannot configure LightDM"
msgstr "نمی‌توان LightDM را پیکربندی کرد"

#: src/modules/displaymanager/main.py:736
msgid "No LightDM greeter installed."
msgstr "هیچ خوش‌آمدگوی LightDMای نصب نشده."

#: src/modules/displaymanager/main.py:767
msgid "Cannot write SLIM configuration file"
msgstr "نمی‌توان پروندهٔ پیکربندی LightDM را نوشت"

#: src/modules/displaymanager/main.py:768
msgid "SLIM config file {!s} does not exist"
msgstr "پروندهٔ پیکربندی {!s} وجود ندارد"

#: src/modules/displaymanager/main.py:894
msgid "No display managers selected for the displaymanager module."
msgstr "هیچ مدیر نمایشی برای پیمانهٔ displaymanager گزیده نشده."

#: src/modules/displaymanager/main.py:895
msgid ""
"The displaymanagers list is empty or undefined in both globalstorage and "
"displaymanager.conf."
msgstr ""

#: src/modules/displaymanager/main.py:977
msgid "Display manager configuration was incomplete"
msgstr "پیکربندی مدیر نمایش کامل نبود"

#: src/modules/initcpiocfg/main.py:28
msgid "Configuring mkinitcpio."
msgstr "پیکربندی mkinitcpio."

#: src/modules/initcpiocfg/main.py:203
#: src/modules/luksopenswaphookcfg/main.py:91
#: src/modules/initramfscfg/main.py:90 src/modules/openrcdmcryptcfg/main.py:77
#: src/modules/fstab/main.py:368 src/modules/localecfg/main.py:136
#: src/modules/networkcfg/main.py:40
msgid "No root mount point is given for <pre>{!s}</pre> to use."
msgstr "هیچ نقطهٔ اتّصال ریشه‌ای برای استفادهٔ <pre>{!s}</pre> داده نشده."

#: src/modules/luksopenswaphookcfg/main.py:26
msgid "Configuring encrypted swap."
msgstr "در حال پیکربندی مبادلهٔ رمزشده."

#: src/modules/rawfs/main.py:26
msgid "Installing data."
msgstr "داده‌های نصب"

#: src/modules/services-openrc/main.py:29
msgid "Configure OpenRC services"
msgstr "پیکربندی خدمات OpenRC"

#: src/modules/services-openrc/main.py:57
msgid "Cannot add service {name!s} to run-level {level!s}."
msgstr "نمی‌توان خدمت {name!s} را به سطح اجرایی {level!s} افزود."

#: src/modules/services-openrc/main.py:59
msgid "Cannot remove service {name!s} from run-level {level!s}."
msgstr "نمی‌توان خدمت {name!s} را از سطح اجرایی {level!s} برداشت."

#: src/modules/services-openrc/main.py:61
msgid ""
"Unknown service-action <code>{arg!s}</code> for service {name!s} in run-"
"level {level!s}."
msgstr ""

#: src/modules/services-openrc/main.py:94
msgid ""
"<code>rc-update {arg!s}</code> call in chroot returned error code {num!s}."
msgstr ""

#: src/modules/services-openrc/main.py:101
msgid "Target runlevel does not exist"
msgstr "سطح اجرایی هدف وجود ندارد."

#: src/modules/services-openrc/main.py:102
msgid ""
"The path for runlevel {level!s} is <code>{path!s}</code>, which does not "
"exist."
msgstr ""

#: src/modules/services-openrc/main.py:110
msgid "Target service does not exist"
msgstr "خدمت هدف وجود ندارد"

#: src/modules/services-openrc/main.py:111
msgid ""
"The path for service {name!s} is <code>{path!s}</code>, which does not "
"exist."
msgstr ""

#: src/modules/plymouthcfg/main.py:27
msgid "Configure Plymouth theme"
msgstr "در حال پیکربندی زمینهٔ پلی‌موث"

#: src/modules/packages/main.py:50 src/modules/packages/main.py:59
#: src/modules/packages/main.py:69
msgid "Install packages."
msgstr "نصب بسته‌ها."

#: src/modules/packages/main.py:57
#, python-format
msgid "Processing packages (%(count)d / %(total)d)"
msgstr "در حال پردازش بسته‌ها (%(count)d/%(total)d)"

#: src/modules/packages/main.py:62
#, python-format
msgid "Installing one package."
msgid_plural "Installing %(num)d packages."
msgstr[0] "در حال نصب یک بسته."
msgstr[1] "در حال نصب %(num)d بسته."

#: src/modules/packages/main.py:65
#, python-format
msgid "Removing one package."
msgid_plural "Removing %(num)d packages."
msgstr[0] "در حال برداشتن یک بسته."
msgstr[1] "در حال برداشتن %(num)d بسته."

#: src/modules/bootloader/main.py:42
msgid "Install bootloader."
msgstr "نصب بارکنندهٔ راه‌اندازی."

#: src/modules/hwclock/main.py:26
msgid "Setting hardware clock."
msgstr "در حال تنظیم ساعت سخت‌افزاری."

#: src/modules/mkinitfs/main.py:27
msgid "Creating initramfs with mkinitfs."
msgstr ""

#: src/modules/mkinitfs/main.py:49
msgid "Failed to run mkinitfs on the target"
msgstr ""

#: src/modules/mkinitfs/main.py:50 src/modules/dracut/main.py:50
msgid "The exit code was {}"
msgstr "رمز خروج {} بود"

#: src/modules/dracut/main.py:27
msgid "Creating initramfs with dracut."
msgstr "در حال ایجاد initramfs با dracut."

#: src/modules/dracut/main.py:49
msgid "Failed to run dracut on the target"
msgstr "شکست در اجرای dracut روی هدف"

#: src/modules/initramfscfg/main.py:32
msgid "Configuring initramfs."
msgstr "در حال پیکربندی initramfs."

#: src/modules/openrcdmcryptcfg/main.py:26
msgid "Configuring OpenRC dmcrypt service."
msgstr "در حال پیکربندی خدمت dmcrypt OpenRC."

#: src/modules/fstab/main.py:29
msgid "Writing fstab."
msgstr "در حال نوشتن fstab."

#: src/modules/dummypython/main.py:35
msgid "Dummy python job."
msgstr "کار پایتونی الکی."

#: src/modules/dummypython/main.py:37 src/modules/dummypython/main.py:93
#: src/modules/dummypython/main.py:94
msgid "Dummy python step {}"
msgstr "گام پایتونی الکی {}"

#: src/modules/localecfg/main.py:30
msgid "Configuring locales."
msgstr "پیکربندی مکانها"

#: src/modules/networkcfg/main.py:28
msgid "Saving network configuration."
msgstr "در حال ذخیرهٔ پیکربندی شبکه."
