# SOME DESCRIPTIVE TITLE.
# Copyright (C) YEAR THE PACKAGE'S COPYRIGHT HOLDER
# This file is distributed under the same license as the PACKAGE package.
# FIRST AUTHOR <EMAIL@ADDRESS>, YEAR.
# 
# Translators:
# Panwar108 <caspian7pena@gmail.com>, 2022
# 
#, fuzzy
msgid ""
msgstr ""
"Project-Id-Version: PACKAGE VERSION\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2023-09-28 22:49+0200\n"
"PO-Revision-Date: 2017-08-09 10:34+0000\n"
"Last-Translator: Panwar108 <caspian7pena@gmail.com>, 2022\n"
"Language-Team: Hindi (https://app.transifex.com/calamares/teams/20061/hi/)\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Language: hi\n"
"Plural-Forms: nplurals=2; plural=(n != 1);\n"

#: src/modules/bootloader/main.py:46
msgid "Install bootloader."
msgstr "बूट लोडर इंस्टॉल करना।"

#: src/modules/bootloader/main.py:644
msgid "Failed to install grub, no partitions defined in global storage"
msgstr "grub इंस्टॉल करना विफल, सर्वत्र संचयन में कोई विभाजन परिभाषित नहीं है"

#: src/modules/bootloader/main.py:899
msgid "Bootloader installation error"
msgstr "बूट लोडर इंस्टॉल त्रुटि"

#: src/modules/bootloader/main.py:900
msgid ""
"The bootloader could not be installed. The installation command "
"<pre>{!s}</pre> returned error code {!s}."
msgstr ""
"बूट लोडर इंस्टॉल करना विफल। इंस्टॉल कमांड <pre>{!s}</pre> हेतु त्रुटि कोड "
"{!s} प्राप्त।"

#: src/modules/displaymanager/main.py:509
msgid "Cannot write LXDM configuration file"
msgstr "LXDM विन्यास फ़ाइल राइट नहीं की जा सकती"

#: src/modules/displaymanager/main.py:510
msgid "LXDM config file {!s} does not exist"
msgstr "LXDM विन्यास फ़ाइल {!s} मौजूद नहीं है"

#: src/modules/displaymanager/main.py:598
msgid "Cannot write LightDM configuration file"
msgstr "LightDM विन्यास फ़ाइल राइट नहीं की जा सकती"

#: src/modules/displaymanager/main.py:599
msgid "LightDM config file {!s} does not exist"
msgstr "LightDM विन्यास फ़ाइल {!s} मौजूद नहीं है"

#: src/modules/displaymanager/main.py:684
msgid "Cannot configure LightDM"
msgstr "LightDM को विन्यस्त नहीं किया जा सकता"

#: src/modules/displaymanager/main.py:685
msgid "No LightDM greeter installed."
msgstr "कोई LightDM लॉगिन स्क्रीन इंस्टॉल नहीं है।"

#: src/modules/displaymanager/main.py:716
msgid "Cannot write SLIM configuration file"
msgstr "SLIM विन्यास फ़ाइल राइट नहीं की जा सकती"

#: src/modules/displaymanager/main.py:717
msgid "SLIM config file {!s} does not exist"
msgstr "SLIM विन्यास फ़ाइल {!s} मौजूद नहीं है"

#: src/modules/displaymanager/main.py:935
msgid "No display managers selected for the displaymanager module."
msgstr "चयनित डिस्प्ले प्रबंधक मॉड्यूल हेतु कोई डिस्प्ले प्रबंधक नहीं मिला।"

#: src/modules/displaymanager/main.py:936
msgid ""
"The displaymanagers list is empty or undefined in both globalstorage and "
"displaymanager.conf."
msgstr ""
"globalstorage व displaymanager.conf में डिस्प्ले प्रबंधक सूची रिक्त या "
"अपरिभाषित है।"

#: src/modules/displaymanager/main.py:1023
msgid "Display manager configuration was incomplete"
msgstr "डिस्प्ले प्रबंधक विन्यास अधूरा था"

#: src/modules/dracut/main.py:29
msgid "Creating initramfs with dracut."
msgstr "dracut के साथ initramfs बनाना।"

#: src/modules/dracut/main.py:63
msgid "Failed to run dracut"
msgstr ""

#: src/modules/dracut/main.py:64
#, python-brace-format
msgid "Dracut failed to run on the target with return code: {return_code}"
msgstr ""

#: src/modules/dummypython/main.py:35
msgid "Dummy python job."
msgstr "डमी पाइथन प्रक्रिया ।"

#: src/modules/dummypython/main.py:37 src/modules/dummypython/main.py:93
#: src/modules/dummypython/main.py:94
msgid "Dummy python step {}"
msgstr "डमी पाइथन प्रक्रिया की चरण संख्या {}"

#: src/modules/fstab/main.py:28
msgid "Writing fstab."
msgstr "fstab पर राइट करना।"

#: src/modules/fstab/main.py:377 src/modules/fstab/main.py:383
#: src/modules/fstab/main.py:411 src/modules/initcpiocfg/main.py:256
#: src/modules/initcpiocfg/main.py:260 src/modules/initramfscfg/main.py:85
#: src/modules/initramfscfg/main.py:89 src/modules/localecfg/main.py:140
#: src/modules/mount/main.py:329 src/modules/networkcfg/main.py:105
#: src/modules/openrcdmcryptcfg/main.py:72
#: src/modules/openrcdmcryptcfg/main.py:76 src/modules/rawfs/main.py:164
msgid "Configuration Error"
msgstr "विन्यास त्रुटि"

#: src/modules/fstab/main.py:378 src/modules/initramfscfg/main.py:86
#: src/modules/mount/main.py:330 src/modules/openrcdmcryptcfg/main.py:73
#: src/modules/rawfs/main.py:165
msgid "No partitions are defined for <pre>{!s}</pre> to use."
msgstr "<pre>{!s}</pre> के उपयोग हेतु कोई विभाजन परिभाषित नहीं हैं।"

#: src/modules/fstab/main.py:384 src/modules/initramfscfg/main.py:90
#: src/modules/localecfg/main.py:141 src/modules/networkcfg/main.py:106
#: src/modules/openrcdmcryptcfg/main.py:77
msgid "No root mount point is given for <pre>{!s}</pre> to use."
msgstr ""
"<pre>{!s}</pre> के उपयोग हेतु कोई रुट माउंट पॉइंट प्रदान नहीं किया गया।"

#: src/modules/fstab/main.py:412
msgid "No <pre>{!s}</pre> configuration is given for <pre>{!s}</pre> to use."
msgstr ""
"कोई <pre>{!s}</pre> विन्यास प्रदान नहीं किया गया <pre>{!s}</pre> के उपयोग "
"हेतु।"

#: src/modules/grubcfg/main.py:29
msgid "Configure GRUB."
msgstr "GRUB विन्यस्त करना।"

#: src/modules/hwclock/main.py:26
msgid "Setting hardware clock."
msgstr "हार्डवेयर घड़ी सेट करना।"

#: src/modules/initcpiocfg/main.py:27
msgid "Configuring mkinitcpio."
msgstr "mkinitcpio को विन्यस्त करना।"

#: src/modules/initcpiocfg/main.py:257
msgid "No partitions are defined for <pre>initcpiocfg</pre>."
msgstr ""

#: src/modules/initcpiocfg/main.py:261
msgid "No root mount point for <pre>initcpiocfg</pre>."
msgstr ""

#: src/modules/initramfscfg/main.py:32
msgid "Configuring initramfs."
msgstr "initramfs को विन्यस्त करना। "

#: src/modules/localecfg/main.py:31
msgid "Configuring locales."
msgstr "स्थानिकी को विन्यस्त करना।"

#: src/modules/mkinitfs/main.py:27
msgid "Creating initramfs with mkinitfs."
msgstr "mkinitfs के साथ initramfs बनाना।"

#: src/modules/mkinitfs/main.py:49
msgid "Failed to run mkinitfs on the target"
msgstr "लक्ष्य पर mkinitfs निष्पादन विफल"

#: src/modules/mkinitfs/main.py:50
msgid "The exit code was {}"
msgstr "त्रुटि कोड  {}"

#: src/modules/mount/main.py:43
msgid "Mounting partitions."
msgstr "विभाजन माउंट करना।"

#: src/modules/mount/main.py:164 src/modules/mount/main.py:200
msgid "Internal error mounting zfs datasets"
msgstr "zfs डेटासेट माउंट करते समय आंतरिक त्रुटि"

#: src/modules/mount/main.py:176
msgid "Failed to import zpool"
msgstr "zpool आयात विफल"

#: src/modules/mount/main.py:192
msgid "Failed to unlock zpool"
msgstr "zpool अनलॉक करना विफल"

#: src/modules/mount/main.py:209 src/modules/mount/main.py:214
msgid "Failed to set zfs mountpoint"
msgstr "zfs माउंट पॉइंट निर्धारण विफल"

#: src/modules/mount/main.py:365
msgid "zfs mounting error"
msgstr "zfs माउंट संबंधी त्रुटि"

#: src/modules/networkcfg/main.py:29
msgid "Saving network configuration."
msgstr "नेटवर्क विन्यास सेटिंग्स संचित करना।"

#: src/modules/openrcdmcryptcfg/main.py:26
msgid "Configuring OpenRC dmcrypt service."
msgstr "OpenRC dmcrypt सेवा विन्यस्त करना।"

#: src/modules/packages/main.py:54 src/modules/packages/main.py:65
#: src/modules/packages/main.py:75
msgid "Install packages."
msgstr "पैकेज इंस्टॉल करना।"

#: src/modules/packages/main.py:63
#, python-format
msgid "Processing packages (%(count)d / %(total)d)"
msgstr "पैकेज (%(count)d / %(total)d) संसाधित किए जा रहे हैं"

#: src/modules/packages/main.py:68
#, python-format
msgid "Installing one package."
msgid_plural "Installing %(num)d packages."
msgstr[0] "एक पैकेज इंस्टॉल किया जा रहा है।"
msgstr[1] "%(num)d पैकेज इंस्टॉल किए जा रहे हैं।"

#: src/modules/packages/main.py:71
#, python-format
msgid "Removing one package."
msgid_plural "Removing %(num)d packages."
msgstr[0] "एक पैकेज हटाया जा रहा है।"
msgstr[1] "%(num)d पैकेज हटाए जा रहे हैं।"

#: src/modules/packages/main.py:740 src/modules/packages/main.py:752
#: src/modules/packages/main.py:780
msgid "Package Manager error"
msgstr "पैकेज प्रबंधक त्रुटि"

#: src/modules/packages/main.py:741
msgid ""
"The package manager could not prepare updates. The command <pre>{!s}</pre> "
"returned error code {!s}."
msgstr ""
"पैकेज प्रबंधक द्वारा अपडेट तैयार करना विफल। कमांड <pre>{!s}</pre> हेतु "
"त्रुटि कोड {!s} प्राप्त।"

#: src/modules/packages/main.py:753
msgid ""
"The package manager could not update the system. The command <pre>{!s}</pre>"
" returned error code {!s}."
msgstr ""
"पैकेज प्रबंधक द्वारा सिस्टम अपडेट करना विफल। कमांड <pre>{!s}</pre> हेतु "
"त्रुटि कोड {!s} प्राप्त।"

#: src/modules/packages/main.py:781
msgid ""
"The package manager could not make changes to the installed system. The "
"command <pre>{!s}</pre> returned error code {!s}."
msgstr ""
"पैकेज प्रबंधक द्वारा इंस्टॉल हो रखें सिस्टम पर परिवर्तन करना विफल। कमांड "
"<pre>{!s}</pre> हेतु त्रुटि कोड {!s} प्राप्त।"

#: src/modules/plymouthcfg/main.py:27
msgid "Configure Plymouth theme"
msgstr "Plymouth थीम विन्यस्त करना "

#: src/modules/rawfs/main.py:26
msgid "Installing data."
msgstr "डाटा इंस्टॉल करना।"

#: src/modules/services-openrc/main.py:29
msgid "Configure OpenRC services"
msgstr "OpenRC सेवाएँ विन्यस्त करना"

#: src/modules/services-openrc/main.py:57
msgid "Cannot add service {name!s} to run-level {level!s}."
msgstr "रन-लेवल {level!s} में सेवा {name!s} को जोड़ा नहीं जा सका।"

#: src/modules/services-openrc/main.py:59
msgid "Cannot remove service {name!s} from run-level {level!s}."
msgstr "रन-लेवल {level!s} में सेवा {name!s} को हटाया नहीं जा सका।"

#: src/modules/services-openrc/main.py:61
msgid ""
"Unknown service-action <code>{arg!s}</code> for service {name!s} in run-"
"level {level!s}."
msgstr ""
"रन-लेवल {level!s} में सेवा {name!s} हेतु अज्ञात सेवा-कार्य "
"<code>{arg!s}</code>।"

#: src/modules/services-openrc/main.py:93
msgid "Cannot modify service"
msgstr "सेवा को संशोधित नहीं किया जा सकता"

#: src/modules/services-openrc/main.py:94
msgid ""
"<code>rc-update {arg!s}</code> call in chroot returned error code {num!s}."
msgstr "chroot में <code> rc-update {arg!s}</code> कॉल त्रुटि कोड {num!s}।"

#: src/modules/services-openrc/main.py:101
msgid "Target runlevel does not exist"
msgstr "लक्षित रनलेवल मौजूद नहीं है"

#: src/modules/services-openrc/main.py:102
msgid ""
"The path for runlevel {level!s} is <code>{path!s}</code>, which does not "
"exist."
msgstr ""
"रनलेवल {level!s} हेतु पथ <code>{path!s}</code> है, जो कि मौजूद नहीं है।"

#: src/modules/services-openrc/main.py:110
msgid "Target service does not exist"
msgstr "लक्षित सेवा मौजूद नहीं है"

#: src/modules/services-openrc/main.py:111
msgid ""
"The path for service {name!s} is <code>{path!s}</code>, which does not "
"exist."
msgstr "सेवा {name!s} हेतु पथ <code>{path!s}</code> है, जो कि मौजूद नहीं है।"

#: src/modules/services-systemd/main.py:26
msgid "Configure systemd units"
msgstr ""

#: src/modules/services-systemd/main.py:64
msgid "Cannot modify unit"
msgstr ""

#: src/modules/services-systemd/main.py:65
msgid ""
"<code>systemctl {_action!s}</code> call in chroot returned error code "
"{_exit_code!s}."
msgstr ""

#: src/modules/services-systemd/main.py:66
msgid "Cannot {_action!s} systemd unit <code>{_name!s}</code>."
msgstr ""

#: src/modules/unpackfs/main.py:34
msgid "Filling up filesystems."
msgstr "फाइल सिस्टम भरना।"

#: src/modules/unpackfs/main.py:254
msgid "rsync failed with error code {}."
msgstr "rsync त्रुटि कोड {} के साथ विफल।"

#: src/modules/unpackfs/main.py:299
msgid "Unpacking image {}/{}, file {}/{}"
msgstr "इमेज फ़ाइल {}/{}, फ़ाइल {}/{} सम्पीड़ित की जा रही है"

#: src/modules/unpackfs/main.py:314
msgid "Starting to unpack {}"
msgstr "{} हेतु संपीड़न प्रक्रिया आरंभ हो रही है "

#: src/modules/unpackfs/main.py:323 src/modules/unpackfs/main.py:467
msgid "Failed to unpack image \"{}\""
msgstr "इमेज फ़ाइल \"{}\" को खोलने में विफल"

#: src/modules/unpackfs/main.py:430
msgid "No mount point for root partition"
msgstr "रुट विभाजन हेतु कोई माउंट पॉइंट नहीं है"

#: src/modules/unpackfs/main.py:431
msgid "globalstorage does not contain a \"rootMountPoint\" key."
msgstr "globalstorage में \"rootMountPoint\" कुंजी नहीं है।"

#: src/modules/unpackfs/main.py:434
msgid "Bad mount point for root partition"
msgstr "रुट विभाजन हेतु ख़राब माउंट पॉइंट"

#: src/modules/unpackfs/main.py:435
msgid "rootMountPoint is \"{}\", which does not exist."
msgstr "rootMountPoint \"{}\" है, जो मौजूद नहीं है।"

#: src/modules/unpackfs/main.py:439 src/modules/unpackfs/main.py:455
#: src/modules/unpackfs/main.py:459 src/modules/unpackfs/main.py:465
#: src/modules/unpackfs/main.py:480
msgid "Bad unpackfs configuration"
msgstr "विकृत unpackfs विन्यास"

#: src/modules/unpackfs/main.py:440
msgid "There is no configuration information."
msgstr "विन्यास संबंधी कोई सूचना नहीं है।"

#: src/modules/unpackfs/main.py:456
msgid "The filesystem for \"{}\" ({}) is not supported by your current kernel"
msgstr "\"{}\" ({}) हेतु फ़ाइल सिस्टम आपके वर्तमान कर्नेल द्वारा समर्थित नहीं है"

#: src/modules/unpackfs/main.py:460
msgid "The source filesystem \"{}\" does not exist"
msgstr "\"{}\" स्रोत फ़ाइल सिस्टम मौजूद नहीं है"

#: src/modules/unpackfs/main.py:466
msgid ""
"Failed to find unsquashfs, make sure you have the squashfs-tools package "
"installed."
msgstr ""
"unsqaushfs खोजने में विफल, सुनिश्चित करें कि squashfs-tools पैकेज इंस्टॉल "
"है।"

#: src/modules/unpackfs/main.py:481
msgid "The destination \"{}\" in the target system is not a directory"
msgstr "लक्षित सिस्टम में \"{}\" स्थान कोई डायरेक्टरी नहीं है"

#: src/modules/zfshostid/main.py:27
msgid "Copying zfs generated hostid."
msgstr ""
