# SOME DESCRIPTIVE TITLE.
# Copyright (C) YEAR THE PACKAGE'S COPYRIGHT HOLDER
# This file is distributed under the same license as the PACKAGE package.
# FIRST AUTHOR <EMAIL@ADDRESS>, YEAR.
# 
# Translators:
# Mingcong Bai <jeffbai@aosc.xyz>, 2017
# plantman <weihanlin@live.com>, 2017
# Feng Chao <chaofeng111@qq.com>, 2020
# Bobby Rong <admin@bobby285271.top>, 2020
# Giovanni Schiano-Moriello, 2022
# 玉堂白鹤 <yjwork@qq.com>, 2022
# OkayPJ <1535253694@qq.com>, 2023
# 
#, fuzzy
msgid ""
msgstr ""
"Project-Id-Version: PACKAGE VERSION\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2023-09-28 22:49+0200\n"
"PO-Revision-Date: 2017-08-09 10:34+0000\n"
"Last-Translator: OkayPJ <1535253694@qq.com>, 2023\n"
"Language-Team: Chinese (China) (https://app.transifex.com/calamares/teams/20061/zh_CN/)\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Language: zh_CN\n"
"Plural-Forms: nplurals=1; plural=0;\n"

#: src/modules/bootloader/main.py:46
msgid "Install bootloader."
msgstr "安装启动加载器。"

#: src/modules/bootloader/main.py:644
msgid "Failed to install grub, no partitions defined in global storage"
msgstr "无法安装 grub，全局存储中未定义分区"

#: src/modules/bootloader/main.py:899
msgid "Bootloader installation error"
msgstr "启动加载器安装出错"

#: src/modules/bootloader/main.py:900
msgid ""
"The bootloader could not be installed. The installation command "
"<pre>{!s}</pre> returned error code {!s}."
msgstr "无法安装启动加载器。安装命令<pre>{!s}</pre>返回错误代码 {!s}。"

#: src/modules/displaymanager/main.py:509
msgid "Cannot write LXDM configuration file"
msgstr "无法写入 LXDM 配置文件"

#: src/modules/displaymanager/main.py:510
msgid "LXDM config file {!s} does not exist"
msgstr "LXDM 配置文件 {!s} 不存在"

#: src/modules/displaymanager/main.py:598
msgid "Cannot write LightDM configuration file"
msgstr "无法写入 LightDM 配置文件"

#: src/modules/displaymanager/main.py:599
msgid "LightDM config file {!s} does not exist"
msgstr "LightDM 配置文件 {!s} 不存在"

#: src/modules/displaymanager/main.py:684
msgid "Cannot configure LightDM"
msgstr "无法配置 LightDM"

#: src/modules/displaymanager/main.py:685
msgid "No LightDM greeter installed."
msgstr "未安装 LightDM 欢迎程序。"

#: src/modules/displaymanager/main.py:716
msgid "Cannot write SLIM configuration file"
msgstr "无法写入 SLIM 配置文件"

#: src/modules/displaymanager/main.py:717
msgid "SLIM config file {!s} does not exist"
msgstr "SLIM 配置文件 {!s} 不存在"

#: src/modules/displaymanager/main.py:935
msgid "No display managers selected for the displaymanager module."
msgstr "显示管理器模块中未选择显示管理器。"

#: src/modules/displaymanager/main.py:936
msgid ""
"The displaymanagers list is empty or undefined in both globalstorage and "
"displaymanager.conf."
msgstr "globalstorage 和 displaymanager.conf 配置文件中都没有配置显示管理器。"

#: src/modules/displaymanager/main.py:1023
msgid "Display manager configuration was incomplete"
msgstr "显示管理器配置不完全"

#: src/modules/dracut/main.py:29
msgid "Creating initramfs with dracut."
msgstr "用 dracut 创建 initramfs."

#: src/modules/dracut/main.py:63
msgid "Failed to run dracut"
msgstr ""

#: src/modules/dracut/main.py:64
#, python-brace-format
msgid "Dracut failed to run on the target with return code: {return_code}"
msgstr ""

#: src/modules/dummypython/main.py:35
msgid "Dummy python job."
msgstr "占位 Python 任务。"

#: src/modules/dummypython/main.py:37 src/modules/dummypython/main.py:93
#: src/modules/dummypython/main.py:94
msgid "Dummy python step {}"
msgstr "占位 Python 步骤 {}"

#: src/modules/fstab/main.py:28
msgid "Writing fstab."
msgstr "正在写入 fstab。"

#: src/modules/fstab/main.py:377 src/modules/fstab/main.py:383
#: src/modules/fstab/main.py:411 src/modules/initcpiocfg/main.py:256
#: src/modules/initcpiocfg/main.py:260 src/modules/initramfscfg/main.py:85
#: src/modules/initramfscfg/main.py:89 src/modules/localecfg/main.py:140
#: src/modules/mount/main.py:329 src/modules/networkcfg/main.py:105
#: src/modules/openrcdmcryptcfg/main.py:72
#: src/modules/openrcdmcryptcfg/main.py:76 src/modules/rawfs/main.py:164
msgid "Configuration Error"
msgstr "配置错误"

#: src/modules/fstab/main.py:378 src/modules/initramfscfg/main.py:86
#: src/modules/mount/main.py:330 src/modules/openrcdmcryptcfg/main.py:73
#: src/modules/rawfs/main.py:165
msgid "No partitions are defined for <pre>{!s}</pre> to use."
msgstr "没有分配分区给 <pre>{!s}</pre>。"

#: src/modules/fstab/main.py:384 src/modules/initramfscfg/main.py:90
#: src/modules/localecfg/main.py:141 src/modules/networkcfg/main.py:106
#: src/modules/openrcdmcryptcfg/main.py:77
msgid "No root mount point is given for <pre>{!s}</pre> to use."
msgstr " 未设置 <pre>{!s}</pre> 要使用的根挂载点。"

#: src/modules/fstab/main.py:412
msgid "No <pre>{!s}</pre> configuration is given for <pre>{!s}</pre> to use."
msgstr "无 <pre>{!s}</pre> 配置可供 <pre>{!s}</pre> 使用。"

#: src/modules/grubcfg/main.py:29
msgid "Configure GRUB."
msgstr "配置 GRUB."

#: src/modules/hwclock/main.py:26
msgid "Setting hardware clock."
msgstr "设置硬件时钟。"

#: src/modules/initcpiocfg/main.py:27
msgid "Configuring mkinitcpio."
msgstr "配置 mkinitcpio."

#: src/modules/initcpiocfg/main.py:257
msgid "No partitions are defined for <pre>initcpiocfg</pre>."
msgstr ""

#: src/modules/initcpiocfg/main.py:261
msgid "No root mount point for <pre>initcpiocfg</pre>."
msgstr ""

#: src/modules/initramfscfg/main.py:32
msgid "Configuring initramfs."
msgstr "正在配置初始内存文件系统。"

#: src/modules/localecfg/main.py:31
msgid "Configuring locales."
msgstr "正在进行本地化配置。"

#: src/modules/mkinitfs/main.py:27
msgid "Creating initramfs with mkinitfs."
msgstr "正在用 mkinitfs 创建initramfs。"

#: src/modules/mkinitfs/main.py:49
msgid "Failed to run mkinitfs on the target"
msgstr "无法在目标中运行 mkinitfs"

#: src/modules/mkinitfs/main.py:50
msgid "The exit code was {}"
msgstr "退出码是 {}"

#: src/modules/mount/main.py:43
msgid "Mounting partitions."
msgstr "挂载分区。"

#: src/modules/mount/main.py:164 src/modules/mount/main.py:200
msgid "Internal error mounting zfs datasets"
msgstr "装载 zfs 数据集时出现内部错误"

#: src/modules/mount/main.py:176
msgid "Failed to import zpool"
msgstr "导入 zpool 失败"

#: src/modules/mount/main.py:192
msgid "Failed to unlock zpool"
msgstr "解锁 zpool 失败"

#: src/modules/mount/main.py:209 src/modules/mount/main.py:214
msgid "Failed to set zfs mountpoint"
msgstr "设置 zfs 挂载点失败"

#: src/modules/mount/main.py:365
msgid "zfs mounting error"
msgstr "zfs 挂载出错"

#: src/modules/networkcfg/main.py:29
msgid "Saving network configuration."
msgstr "正在保存网络配置。"

#: src/modules/openrcdmcryptcfg/main.py:26
msgid "Configuring OpenRC dmcrypt service."
msgstr "配置 OpenRC dmcrypt 服务。"

#: src/modules/packages/main.py:54 src/modules/packages/main.py:65
#: src/modules/packages/main.py:75
msgid "Install packages."
msgstr "安装软件包。"

#: src/modules/packages/main.py:63
#, python-format
msgid "Processing packages (%(count)d / %(total)d)"
msgstr "软件包处理中（%(count)d/%(total)d）"

#: src/modules/packages/main.py:68
#, python-format
msgid "Installing one package."
msgid_plural "Installing %(num)d packages."
msgstr[0] "安装%(num)d软件包。"

#: src/modules/packages/main.py:71
#, python-format
msgid "Removing one package."
msgid_plural "Removing %(num)d packages."
msgstr[0] "移除%(num)d软件包。"

#: src/modules/packages/main.py:740 src/modules/packages/main.py:752
#: src/modules/packages/main.py:780
msgid "Package Manager error"
msgstr "软件包管理器错误"

#: src/modules/packages/main.py:741
msgid ""
"The package manager could not prepare updates. The command <pre>{!s}</pre> "
"returned error code {!s}."
msgstr "软件包管理器无法准备更新。命令<pre>{!s}</pre>返回错误代码{!s}。"

#: src/modules/packages/main.py:753
msgid ""
"The package manager could not update the system. The command <pre>{!s}</pre>"
" returned error code {!s}."
msgstr "软件包管理器无法更新系统。命令<pre>{!s}</pre>返回错误代码{!s}。"

#: src/modules/packages/main.py:781
msgid ""
"The package manager could not make changes to the installed system. The "
"command <pre>{!s}</pre> returned error code {!s}."
msgstr "软件包管理器无法对已安装的系统进行更改。命令<pre>{!s}</pre>返回错误代码{!s}。"

#: src/modules/plymouthcfg/main.py:27
msgid "Configure Plymouth theme"
msgstr "配置 Plymouth 主题"

#: src/modules/rawfs/main.py:26
msgid "Installing data."
msgstr "安装数据."

#: src/modules/services-openrc/main.py:29
msgid "Configure OpenRC services"
msgstr "配置 OpenRC 服务。"

#: src/modules/services-openrc/main.py:57
msgid "Cannot add service {name!s} to run-level {level!s}."
msgstr "无法将服务 {name!s} 加入 {level!s} 运行级别."

#: src/modules/services-openrc/main.py:59
msgid "Cannot remove service {name!s} from run-level {level!s}."
msgstr "无法从 {level!s} 运行级别中删除服务 {name!s}。"

#: src/modules/services-openrc/main.py:61
msgid ""
"Unknown service-action <code>{arg!s}</code> for service {name!s} in run-"
"level {level!s}."
msgstr "未知的服务动作 <code>{arg!s}</code>，服务名: {name!s}，运行级别: {level!s}."

#: src/modules/services-openrc/main.py:93
msgid "Cannot modify service"
msgstr "无法修改服务"

#: src/modules/services-openrc/main.py:94
msgid ""
"<code>rc-update {arg!s}</code> call in chroot returned error code {num!s}."
msgstr "chroot 中运行的 <code>rc-update {arg!s}</code> 返回错误 {num!s}."

#: src/modules/services-openrc/main.py:101
msgid "Target runlevel does not exist"
msgstr "目标运行级别不存在。"

#: src/modules/services-openrc/main.py:102
msgid ""
"The path for runlevel {level!s} is <code>{path!s}</code>, which does not "
"exist."
msgstr "运行级别 {level!s} 所在目录 <code>{path!s}</code> 不存在。"

#: src/modules/services-openrc/main.py:110
msgid "Target service does not exist"
msgstr "目标服务不存在"

#: src/modules/services-openrc/main.py:111
msgid ""
"The path for service {name!s} is <code>{path!s}</code>, which does not "
"exist."
msgstr "服务 {name!s} 的路径 <code>{path!s}</code> 不存在。"

#: src/modules/services-systemd/main.py:26
msgid "Configure systemd units"
msgstr "配置 systemd 单元"

#: src/modules/services-systemd/main.py:64
msgid "Cannot modify unit"
msgstr "无法修改单元"

#: src/modules/services-systemd/main.py:65
msgid ""
"<code>systemctl {_action!s}</code> call in chroot returned error code "
"{_exit_code!s}."
msgstr "chroot 中运行的 <code>systemctl {_action!s}</code> 返回错误 {_exit_code!s}。"

#: src/modules/services-systemd/main.py:66
msgid "Cannot {_action!s} systemd unit <code>{_name!s}</code>."
msgstr ""

#: src/modules/unpackfs/main.py:34
msgid "Filling up filesystems."
msgstr "写入文件系统。"

#: src/modules/unpackfs/main.py:254
msgid "rsync failed with error code {}."
msgstr "rsync 报错，错误码 {}."

#: src/modules/unpackfs/main.py:299
msgid "Unpacking image {}/{}, file {}/{}"
msgstr "解压镜像 {}/{}，文件{}/{}"

#: src/modules/unpackfs/main.py:314
msgid "Starting to unpack {}"
msgstr "开始解压 {}"

#: src/modules/unpackfs/main.py:323 src/modules/unpackfs/main.py:467
msgid "Failed to unpack image \"{}\""
msgstr "解压镜像失败 \"{}\""

#: src/modules/unpackfs/main.py:430
msgid "No mount point for root partition"
msgstr "无 root 分区挂载点"

#: src/modules/unpackfs/main.py:431
msgid "globalstorage does not contain a \"rootMountPoint\" key."
msgstr "globalstorage（全局存储）中不包含 \"rootMountPoint\"（root挂载点）键。"

#: src/modules/unpackfs/main.py:434
msgid "Bad mount point for root partition"
msgstr "错误的 root 分区挂载点"

#: src/modules/unpackfs/main.py:435
msgid "rootMountPoint is \"{}\", which does not exist."
msgstr "rootMountPoint（root挂载点）是 \"{}\"，其不存在。"

#: src/modules/unpackfs/main.py:439 src/modules/unpackfs/main.py:455
#: src/modules/unpackfs/main.py:459 src/modules/unpackfs/main.py:465
#: src/modules/unpackfs/main.py:480
msgid "Bad unpackfs configuration"
msgstr "错误的 unpackfs 解包配置"

#: src/modules/unpackfs/main.py:440
msgid "There is no configuration information."
msgstr "没有配置信息。"

#: src/modules/unpackfs/main.py:456
msgid "The filesystem for \"{}\" ({}) is not supported by your current kernel"
msgstr "你当前的内核不支持文件系统 \"{}\" ({})"

#: src/modules/unpackfs/main.py:460
msgid "The source filesystem \"{}\" does not exist"
msgstr "源文件系统 \"{}\" 不存在"

#: src/modules/unpackfs/main.py:466
msgid ""
"Failed to find unsquashfs, make sure you have the squashfs-tools package "
"installed."
msgstr "寻找 unsquashfs 失败，请确定您已安装 squashfs-tools 软体包。"

#: src/modules/unpackfs/main.py:481
msgid "The destination \"{}\" in the target system is not a directory"
msgstr "目标系统中的 \"{}\" 不是一个目录"

#: src/modules/zfshostid/main.py:27
msgid "Copying zfs generated hostid."
msgstr ""
