# SOME DESCRIPTIVE TITLE.
# Copyright (C) YEAR THE PACKAGE'S COPYRIGHT HOLDER
# This file is distributed under the same license as the PACKAGE package.
# FIRST AUTHOR <EMAIL@ADDRESS>, YEAR.
# 
# Translators:
# Kimmo Kujansuu <mrkujansuu@gmail.com>, 2022
# Jiri Grönroos <jiri.gronroos@iki.fi>, 2022
# 
#, fuzzy
msgid ""
msgstr ""
"Project-Id-Version: PACKAGE VERSION\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2022-05-27 11:18+0200\n"
"PO-Revision-Date: 2017-08-09 10:34+0000\n"
"Last-Translator: Jiri Grönroos <jiri.gronroos@iki.fi>, 2022\n"
"Language-Team: Finnish (Finland) (https://www.transifex.com/calamares/teams/20061/fi_FI/)\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Language: fi_FI\n"
"Plural-Forms: nplurals=2; plural=(n != 1);\n"

#: src/modules/packages/main.py:54 src/modules/packages/main.py:65
#: src/modules/packages/main.py:75
msgid "Install packages."
msgstr "Asenna paketit."

#: src/modules/packages/main.py:63
#, python-format
msgid "Processing packages (%(count)d / %(total)d)"
msgstr "Käsitellään paketteja (%(count)d / %(total)d)"

#: src/modules/packages/main.py:68
#, python-format
msgid "Installing one package."
msgid_plural "Installing %(num)d packages."
msgstr[0] "Asennetaan yhtä pakettia."
msgstr[1] "Asennetaan %(num)d pakettia."

#: src/modules/packages/main.py:71
#, python-format
msgid "Removing one package."
msgid_plural "Removing %(num)d packages."
msgstr[0] "Poistetaan yhtä pakettia."
msgstr[1] "Poistetaan %(num)d pakettia."

#: src/modules/packages/main.py:725 src/modules/packages/main.py:737
#: src/modules/packages/main.py:765
msgid "Package Manager error"
msgstr "Paketinhallinnan virhe"

#: src/modules/packages/main.py:726
msgid ""
"The package manager could not prepare updates. The command <pre>{!s}</pre> "
"returned error code {!s}."
msgstr ""
"Paketinhallinta ei voinut valmistella päivityksiä. Komento <pre>{!s}</pre> "
"palautti virhekoodin {!s}."

#: src/modules/packages/main.py:738
msgid ""
"The package manager could not update the system. The command <pre>{!s}</pre>"
" returned error code {!s}."
msgstr ""
"Paketinhallinta ei voinut päivittää järjestelmää. Komento <pre>{!s}</pre> "
"palautti virhekoodin {!s}."

#: src/modules/packages/main.py:766
msgid ""
"The package manager could not make changes to the installed system. The "
"command <pre>{!s}</pre> returned error code {!s}."
msgstr ""
"Paketinhallinta ei voinut tehdä muutoksia asennettuun järjestelmään. Komento"
" <pre>{!s}</pre> palautti virhekoodin {!s}."

#: src/modules/networkcfg/main.py:29
msgid "Saving network configuration."
msgstr "Tallennetaan verkon määrityksiä."

#: src/modules/networkcfg/main.py:105 src/modules/initcpiocfg/main.py:235
#: src/modules/initcpiocfg/main.py:239 src/modules/openrcdmcryptcfg/main.py:72
#: src/modules/openrcdmcryptcfg/main.py:76 src/modules/localecfg/main.py:140
#: src/modules/mount/main.py:229 src/modules/fstab/main.py:394
#: src/modules/fstab/main.py:400 src/modules/fstab/main.py:428
#: src/modules/initramfscfg/main.py:85 src/modules/initramfscfg/main.py:89
#: src/modules/rawfs/main.py:164
msgid "Configuration Error"
msgstr "Määritysvirhe"

#: src/modules/networkcfg/main.py:106 src/modules/initcpiocfg/main.py:240
#: src/modules/openrcdmcryptcfg/main.py:77 src/modules/localecfg/main.py:141
#: src/modules/fstab/main.py:401 src/modules/initramfscfg/main.py:90
msgid "No root mount point is given for <pre>{!s}</pre> to use."
msgstr "Kohteelle <pre>{!s}</pre> ei ole annettu juuriliitospistettä."

#: src/modules/initcpiocfg/main.py:28
msgid "Configuring mkinitcpio."
msgstr "Määritetään mkinitcpio."

#: src/modules/initcpiocfg/main.py:236 src/modules/openrcdmcryptcfg/main.py:73
#: src/modules/mount/main.py:230 src/modules/fstab/main.py:395
#: src/modules/initramfscfg/main.py:86 src/modules/rawfs/main.py:165
msgid "No partitions are defined for <pre>{!s}</pre> to use."
msgstr "Osioita ei ole määritetty käytettäväksi kohteelle <pre>{!s}</pre> ."

#: src/modules/mkinitfs/main.py:27
msgid "Creating initramfs with mkinitfs."
msgstr "Luodaan initramfs mkinitfs:llä."

#: src/modules/mkinitfs/main.py:49
msgid "Failed to run mkinitfs on the target"
msgstr "mkinitfs:n suorittaminen kohteessa epäonnistui"

#: src/modules/mkinitfs/main.py:50 src/modules/dracut/main.py:50
msgid "The exit code was {}"
msgstr "Poistumiskoodi oli {}"

#: src/modules/openrcdmcryptcfg/main.py:26
msgid "Configuring OpenRC dmcrypt service."
msgstr "Määritetään OpenRC:n dmcrypt-palvelua."

#: src/modules/unpackfs/main.py:34
msgid "Filling up filesystems."
msgstr "Täytetään tiedostojärjestelmiä."

#: src/modules/unpackfs/main.py:254
msgid "rsync failed with error code {}."
msgstr "rsync epäonnistui virhekoodilla {}."

#: src/modules/unpackfs/main.py:299
msgid "Unpacking image {}/{}, file {}/{}"
msgstr "Puretaan levykuvaa {}/{}, tiedosto {}/{}"

#: src/modules/unpackfs/main.py:314
msgid "Starting to unpack {}"
msgstr "Pakkauksen purkaminen alkaa {}"

#: src/modules/unpackfs/main.py:323 src/modules/unpackfs/main.py:467
msgid "Failed to unpack image \"{}\""
msgstr "Levykuvan\"{}\" purkaminen epäonnistui"

#: src/modules/unpackfs/main.py:430
msgid "No mount point for root partition"
msgstr "Ei liitospistettä juuriosiolle"

#: src/modules/unpackfs/main.py:431
msgid "globalstorage does not contain a \"rootMountPoint\" key."
msgstr "globalstorage ei sisällä \"rootMountPoint\"-avainta."

#: src/modules/unpackfs/main.py:434
msgid "Bad mount point for root partition"
msgstr "Virheellinen liitospiste juuriosiolle"

#: src/modules/unpackfs/main.py:435
msgid "rootMountPoint is \"{}\", which does not exist."
msgstr "rootMountPoint on \"{}\", jota ei ole olemassa."

#: src/modules/unpackfs/main.py:439 src/modules/unpackfs/main.py:455
#: src/modules/unpackfs/main.py:459 src/modules/unpackfs/main.py:465
#: src/modules/unpackfs/main.py:480
msgid "Bad unpackfs configuration"
msgstr "Virheellinen unpacckfs-määritys"

#: src/modules/unpackfs/main.py:440
msgid "There is no configuration information."
msgstr "Määritystietoja ei ole."

#: src/modules/unpackfs/main.py:456
msgid "The filesystem for \"{}\" ({}) is not supported by your current kernel"
msgstr "Nykyinen ydin ei tue osion \"{}\" ({}) tiedostojärjestelmää"

#: src/modules/unpackfs/main.py:460
msgid "The source filesystem \"{}\" does not exist"
msgstr "Lähdetiedostojärjestelmää \"{}\" ei ole olemassa"

#: src/modules/unpackfs/main.py:466
msgid ""
"Failed to find unsquashfs, make sure you have the squashfs-tools package "
"installed."
msgstr ""
"Unsquashfs-tiedostoja ei löytynyt, varmista, että paketti squashfs-tools on "
"asennettu."

#: src/modules/unpackfs/main.py:481
msgid "The destination \"{}\" in the target system is not a directory"
msgstr "Kohdejärjestelmän kohde \"{}\"  ei ole hakemisto"

#: src/modules/services-systemd/main.py:26
msgid "Configure systemd services"
msgstr "Määritä systemd-palvelut"

#: src/modules/services-systemd/main.py:59
#: src/modules/services-openrc/main.py:93
msgid "Cannot modify service"
msgstr "Palvelua ei voi muokata"

#: src/modules/services-systemd/main.py:60
msgid ""
"<code>systemctl {arg!s}</code> call in chroot returned error code {num!s}."
msgstr "<code>systemctl {arg!s}</code> chroot palautti virhe koodin {num!s}."

#: src/modules/services-systemd/main.py:63
#: src/modules/services-systemd/main.py:69
msgid "Cannot enable systemd service <code>{name!s}</code>."
msgstr "Systemd-palvelua <code>{name!s}</code> ei voi ottaa käyttöön."

#: src/modules/services-systemd/main.py:65
msgid "Cannot enable systemd target <code>{name!s}</code>."
msgstr "Systemd-kohdetta <code>{name!s}</code> ei voi ottaa käyttöön."

#: src/modules/services-systemd/main.py:67
msgid "Cannot enable systemd timer <code>{name!s}</code>."
msgstr "Systemd-ajastinta <code>{name!s}</code> ei voi ottaa käyttöön."

#: src/modules/services-systemd/main.py:71
msgid "Cannot disable systemd target <code>{name!s}</code>."
msgstr "Systemd-kohdetta <code>{name!s}</code> ei voi poistaa käytöstä."

#: src/modules/services-systemd/main.py:73
msgid "Cannot mask systemd unit <code>{name!s}</code>."
msgstr "Ei voi peittää systemd-yksikköä <code>{name!s}</code>."

#: src/modules/services-systemd/main.py:75
msgid ""
"Unknown systemd commands <code>{command!s}</code> and "
"<code>{suffix!s}</code> for unit {name!s}."
msgstr ""
"Tuntemattomia systemd-komentoja <code>{command!s}</code> ja "
"<code>{suffix!s}</code> yksikölle {name!s}."

#: src/modules/dummypython/main.py:35
msgid "Dummy python job."
msgstr "Dummy-mallinen python-työ."

#: src/modules/dummypython/main.py:37 src/modules/dummypython/main.py:93
#: src/modules/dummypython/main.py:94
msgid "Dummy python step {}"
msgstr "Dummy-mallinen python-vaihe {}"

#: src/modules/bootloader/main.py:43
msgid "Install bootloader."
msgstr "Asenna käynnistyslatain."

#: src/modules/bootloader/main.py:614
msgid "Failed to install grub, no partitions defined in global storage"
msgstr ""
"Grubin asennus epäonnistui, yleisessä levytilassa ei ole määritetty osioita"

#: src/modules/bootloader/main.py:782
msgid "Bootloader installation error"
msgstr "Käynnistyslataimen asennusvirhe"

#: src/modules/bootloader/main.py:783
msgid ""
"The bootloader could not be installed. The installation command "
"<pre>{!s}</pre> returned error code {!s}."
msgstr ""
"Käynnistyslatainta ei voitu asentaa. Asennuskomento <pre>{!s}</pre> palautti"
" virhekoodin {!s}."

#: src/modules/localecfg/main.py:31
msgid "Configuring locales."
msgstr "Määritetään maa-asetuksia."

#: src/modules/mount/main.py:42
msgid "Mounting partitions."
msgstr "Liitetään osioita."

#: src/modules/mount/main.py:88 src/modules/mount/main.py:124
msgid "Internal error mounting zfs datasets"
msgstr "Sisäinen virhe liitettäessä zfs-tietojoukkoa"

#: src/modules/mount/main.py:100
msgid "Failed to import zpool"
msgstr "Zpoolin tuonti epäonnistui"

#: src/modules/mount/main.py:116
msgid "Failed to unlock zpool"
msgstr "Zpoolin lukituksen avaaminen epäonnistui"

#: src/modules/mount/main.py:133 src/modules/mount/main.py:138
msgid "Failed to set zfs mountpoint"
msgstr "Määritys zfs-liitospisteen epäonnistui"

#: src/modules/mount/main.py:253
msgid "zfs mounting error"
msgstr "zfs-liitosvirhe"

#: src/modules/plymouthcfg/main.py:27
msgid "Configure Plymouth theme"
msgstr "Määritä Plymouthin teema"

#: src/modules/fstab/main.py:28
msgid "Writing fstab."
msgstr "Kirjoitetaan fstabiin."

#: src/modules/fstab/main.py:429
msgid "No <pre>{!s}</pre> configuration is given for <pre>{!s}</pre> to use."
msgstr ""
"\"<pre>{!s}</pre>\"-määritystä ei ole annettu käytettäväksi kohteelle "
"<pre>{!s}</pre>."

#: src/modules/services-openrc/main.py:29
msgid "Configure OpenRC services"
msgstr "Määritä OpenRC-palvelut"

#: src/modules/services-openrc/main.py:57
msgid "Cannot add service {name!s} to run-level {level!s}."
msgstr "Palvelua {name!s} ei voi lisätä suorituksen tasolle {level!s}."

#: src/modules/services-openrc/main.py:59
msgid "Cannot remove service {name!s} from run-level {level!s}."
msgstr "Ei voi poistaa palvelua {name!s} suorituksen tasolla {level!s}."

#: src/modules/services-openrc/main.py:61
msgid ""
"Unknown service-action <code>{arg!s}</code> for service {name!s} in run-"
"level {level!s}."
msgstr ""
"Tuntematon  huoltotoiminto<code>{arg!s}</code> palvelun {name!s} "
"palvelutasolle  {level!s}."

#: src/modules/services-openrc/main.py:94
msgid ""
"<code>rc-update {arg!s}</code> call in chroot returned error code {num!s}."
msgstr ""
"<code>rc-update {arg!s}</code> palautti chrootissa virhekoodin {num!s}."

#: src/modules/services-openrc/main.py:101
msgid "Target runlevel does not exist"
msgstr "Kohteen ajotasoa ei ole olemassa"

#: src/modules/services-openrc/main.py:102
msgid ""
"The path for runlevel {level!s} is <code>{path!s}</code>, which does not "
"exist."
msgstr "Ajotason polku {level!s} on <code>{path!s}</code>, jota ei ole."

#: src/modules/services-openrc/main.py:110
msgid "Target service does not exist"
msgstr "Kohdepalvelua ei ole"

#: src/modules/services-openrc/main.py:111
msgid ""
"The path for service {name!s} is <code>{path!s}</code>, which does not "
"exist."
msgstr ""
"Palvelun polku {name!s} on <code>{path!s}</code>,  jota ei ole olemassa."

#: src/modules/dracut/main.py:27
msgid "Creating initramfs with dracut."
msgstr "Luodaan initramfs:ää dracutilla."

#: src/modules/dracut/main.py:49
msgid "Failed to run dracut on the target"
msgstr "Dracutin suorittaminen kohteessa ei onnistunut"

#: src/modules/grubcfg/main.py:28
msgid "Configure GRUB."
msgstr "Määritä GRUB."

#: src/modules/displaymanager/main.py:524
msgid "Cannot write KDM configuration file"
msgstr "KDM-määritystiedostoa ei voi kirjoittaa"

#: src/modules/displaymanager/main.py:525
msgid "KDM config file {!s} does not exist"
msgstr "KDM-määritystiedostoa {!s} ei ole olemassa"

#: src/modules/displaymanager/main.py:586
msgid "Cannot write LXDM configuration file"
msgstr "LXDM-määritystiedostoa ei voi kirjoittaa"

#: src/modules/displaymanager/main.py:587
msgid "LXDM config file {!s} does not exist"
msgstr "LXDM-määritystiedostoa {!s} ei ole olemassa"

#: src/modules/displaymanager/main.py:670
msgid "Cannot write LightDM configuration file"
msgstr "LightDM-määritystiedostoa ei voi kirjoittaa"

#: src/modules/displaymanager/main.py:671
msgid "LightDM config file {!s} does not exist"
msgstr "LightDM-määritystiedostoa {!s} ei ole olemassa"

#: src/modules/displaymanager/main.py:745
msgid "Cannot configure LightDM"
msgstr "LightDM-määritysvirhe"

#: src/modules/displaymanager/main.py:746
msgid "No LightDM greeter installed."
msgstr "LightDM:ää ei ole asennettu."

#: src/modules/displaymanager/main.py:777
msgid "Cannot write SLIM configuration file"
msgstr "SLIM-määritystiedostoa ei voi kirjoittaa"

#: src/modules/displaymanager/main.py:778
msgid "SLIM config file {!s} does not exist"
msgstr "SLIM-määritystiedostoa {!s} ei ole olemassa"

#: src/modules/displaymanager/main.py:992
msgid "No display managers selected for the displaymanager module."
msgstr "Displaymanager-moduulia varten ei ole valittu näytönhallintaa."

#: src/modules/displaymanager/main.py:993
msgid ""
"The displaymanagers list is empty or undefined in both globalstorage and "
"displaymanager.conf."
msgstr ""
"Luettelo on tyhjä tai määrittelemätön, sekä globalstorage, että "
"displaymanager.conf tiedostossa."

#: src/modules/displaymanager/main.py:1075
msgid "Display manager configuration was incomplete"
msgstr "Näytönhallinnan kokoonpano oli puutteellinen"

#: src/modules/initramfscfg/main.py:32
msgid "Configuring initramfs."
msgstr "Määritetään initramfs."

#: src/modules/hwclock/main.py:26
msgid "Setting hardware clock."
msgstr "Asetetaan laitteiston kelloa."

#: src/modules/rawfs/main.py:26
msgid "Installing data."
msgstr "Asennetaan tietoja."
