# SOME DESCRIPTIVE TITLE.
# Copyright (C) YEAR THE PACKAGE'S COPYRIGHT HOLDER
# This file is distributed under the same license as the PACKAGE package.
# FIRST AUTHOR <EMAIL@ADDRESS>, YEAR.
# 
# Translators:
# Ji-Hyeon Gim <potatogim@potatogim.net>, 2018
# Junghee Lee <daemul72@gmail.com>, 2022
# 
#, fuzzy
msgid ""
msgstr ""
"Project-Id-Version: PACKAGE VERSION\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2022-05-27 11:18+0200\n"
"PO-Revision-Date: 2017-08-09 10:34+0000\n"
"Last-Translator: Junghee Lee <daemul72@gmail.com>, 2022\n"
"Language-Team: Korean (https://www.transifex.com/calamares/teams/20061/ko/)\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Language: ko\n"
"Plural-Forms: nplurals=1; plural=0;\n"

#: src/modules/packages/main.py:54 src/modules/packages/main.py:65
#: src/modules/packages/main.py:75
msgid "Install packages."
msgstr "패키지를 설치합니다."

#: src/modules/packages/main.py:63
#, python-format
msgid "Processing packages (%(count)d / %(total)d)"
msgstr "패키지 처리중 (%(count)d / %(total)d)"

#: src/modules/packages/main.py:68
#, python-format
msgid "Installing one package."
msgid_plural "Installing %(num)d packages."
msgstr[0] "%(num)d개의 패키지들을 설치하는 중입니다."

#: src/modules/packages/main.py:71
#, python-format
msgid "Removing one package."
msgid_plural "Removing %(num)d packages."
msgstr[0] "%(num)d개의 패키지들을 제거하는 중입니다."

#: src/modules/packages/main.py:725 src/modules/packages/main.py:737
#: src/modules/packages/main.py:765
msgid "Package Manager error"
msgstr "패키지 관리자 오류"

#: src/modules/packages/main.py:726
msgid ""
"The package manager could not prepare updates. The command <pre>{!s}</pre> "
"returned error code {!s}."
msgstr "패키지 관리자가 업데이트를 준비할 수 없습니다. <pre>{!s}</pre> 명령에서  {!s} 오류 코드를 반환했습니다."

#: src/modules/packages/main.py:738
msgid ""
"The package manager could not update the system. The command <pre>{!s}</pre>"
" returned error code {!s}."
msgstr "패키지 관리자가 시스템을 업데이트할 수 없습니다. <pre>{!s}</pre> 명령에서  {!s} 오류 코드를 반환했습니다."

#: src/modules/packages/main.py:766
msgid ""
"The package manager could not make changes to the installed system. The "
"command <pre>{!s}</pre> returned error code {!s}."
msgstr ""
"패키지 관리자가 설치된 시스템을 변경할 수 없습니다. <pre>{!s}</pre> 명령에서  {!s} 오류 코드를 반환했습니다."

#: src/modules/networkcfg/main.py:29
msgid "Saving network configuration."
msgstr "네트워크 구성 저장 중."

#: src/modules/networkcfg/main.py:105 src/modules/initcpiocfg/main.py:235
#: src/modules/initcpiocfg/main.py:239 src/modules/openrcdmcryptcfg/main.py:72
#: src/modules/openrcdmcryptcfg/main.py:76 src/modules/localecfg/main.py:140
#: src/modules/mount/main.py:229 src/modules/fstab/main.py:394
#: src/modules/fstab/main.py:400 src/modules/fstab/main.py:428
#: src/modules/initramfscfg/main.py:85 src/modules/initramfscfg/main.py:89
#: src/modules/rawfs/main.py:164
msgid "Configuration Error"
msgstr "구성 오류"

#: src/modules/networkcfg/main.py:106 src/modules/initcpiocfg/main.py:240
#: src/modules/openrcdmcryptcfg/main.py:77 src/modules/localecfg/main.py:141
#: src/modules/fstab/main.py:401 src/modules/initramfscfg/main.py:90
msgid "No root mount point is given for <pre>{!s}</pre> to use."
msgstr "<pre>{!s}</pre>에서 사용할 루트 마운트 지점이 제공되지 않음."

#: src/modules/initcpiocfg/main.py:28
msgid "Configuring mkinitcpio."
msgstr "mkinitcpio 구성 중."

#: src/modules/initcpiocfg/main.py:236 src/modules/openrcdmcryptcfg/main.py:73
#: src/modules/mount/main.py:230 src/modules/fstab/main.py:395
#: src/modules/initramfscfg/main.py:86 src/modules/rawfs/main.py:165
msgid "No partitions are defined for <pre>{!s}</pre> to use."
msgstr "사용할 <pre>{!s}</pre>에 대해 정의된 파티션이 없음."

#: src/modules/mkinitfs/main.py:27
msgid "Creating initramfs with mkinitfs."
msgstr "mkinitfs로 initramfs 생성 중."

#: src/modules/mkinitfs/main.py:49
msgid "Failed to run mkinitfs on the target"
msgstr "대상에서 mkinitfs를 실행하지 못했습니다"

#: src/modules/mkinitfs/main.py:50 src/modules/dracut/main.py:50
msgid "The exit code was {}"
msgstr "종료 코드 {}"

#: src/modules/openrcdmcryptcfg/main.py:26
msgid "Configuring OpenRC dmcrypt service."
msgstr "OpenRC dmcrypt 서비스 구성 중."

#: src/modules/unpackfs/main.py:34
msgid "Filling up filesystems."
msgstr "파일 시스템을 채우는 중."

#: src/modules/unpackfs/main.py:254
msgid "rsync failed with error code {}."
msgstr "rsync가 {} 오류 코드로 실패했습니다."

#: src/modules/unpackfs/main.py:299
msgid "Unpacking image {}/{}, file {}/{}"
msgstr "이미지 {}/{}, 파일 {}/{} 압축푸는 중"

#: src/modules/unpackfs/main.py:314
msgid "Starting to unpack {}"
msgstr "{} 압축 풀기 시작 중"

#: src/modules/unpackfs/main.py:323 src/modules/unpackfs/main.py:467
msgid "Failed to unpack image \"{}\""
msgstr "\"{}\" 이미지의 압축을 풀지 못했습니다."

#: src/modules/unpackfs/main.py:430
msgid "No mount point for root partition"
msgstr "루트 파티션에 대한 마운트 위치 없음"

#: src/modules/unpackfs/main.py:431
msgid "globalstorage does not contain a \"rootMountPoint\" key."
msgstr "globalstorage는 \"루트마운트위치\" 키를 포함하지 않습니다."

#: src/modules/unpackfs/main.py:434
msgid "Bad mount point for root partition"
msgstr "루트 파티션에 대한 잘못된 마운트 위치"

#: src/modules/unpackfs/main.py:435
msgid "rootMountPoint is \"{}\", which does not exist."
msgstr "루트마운트위치는 \"{}\"이고, 존재하지 않습니다."

#: src/modules/unpackfs/main.py:439 src/modules/unpackfs/main.py:455
#: src/modules/unpackfs/main.py:459 src/modules/unpackfs/main.py:465
#: src/modules/unpackfs/main.py:480
msgid "Bad unpackfs configuration"
msgstr "unpackfs 구성이 잘못되었습니다."

#: src/modules/unpackfs/main.py:440
msgid "There is no configuration information."
msgstr "구성 정보가 없습니다."

#: src/modules/unpackfs/main.py:456
msgid "The filesystem for \"{}\" ({}) is not supported by your current kernel"
msgstr "\"{}\" ({})에 대한 파일 시스템은 현재 커널에서 지원되지 않습니다."

#: src/modules/unpackfs/main.py:460
msgid "The source filesystem \"{}\" does not exist"
msgstr "\"{}\" 소스 파일시스템은 존재하지 않습니다."

#: src/modules/unpackfs/main.py:466
msgid ""
"Failed to find unsquashfs, make sure you have the squashfs-tools package "
"installed."
msgstr "unsquashfs를 찾지 못했습니다. squashfs-tools 패키지가 설치되어 있는지 확인하십시오."

#: src/modules/unpackfs/main.py:481
msgid "The destination \"{}\" in the target system is not a directory"
msgstr "대상 시스템의 \"{}\" 목적지가 디렉토리가 아닙니다."

#: src/modules/services-systemd/main.py:26
msgid "Configure systemd services"
msgstr "systemd 서비스 구성"

#: src/modules/services-systemd/main.py:59
#: src/modules/services-openrc/main.py:93
msgid "Cannot modify service"
msgstr "서비스를 수정할 수 없음"

#: src/modules/services-systemd/main.py:60
msgid ""
"<code>systemctl {arg!s}</code> call in chroot returned error code {num!s}."
msgstr "chroot에서 <code>systemctl {arg!s}</code> 호출에서오류 코드 {num}를 반환 했습니다."

#: src/modules/services-systemd/main.py:63
#: src/modules/services-systemd/main.py:69
msgid "Cannot enable systemd service <code>{name!s}</code>."
msgstr "<code>{name! s}</code> 시스템 서비스를 활성화 할 수 없습니다."

#: src/modules/services-systemd/main.py:65
msgid "Cannot enable systemd target <code>{name!s}</code>."
msgstr "systemd 대상 <code>{name! s}</code>를 활성화 할 수 없습니다."

#: src/modules/services-systemd/main.py:67
msgid "Cannot enable systemd timer <code>{name!s}</code>."
msgstr "시스템 타이머 <code>{name!s}</code>를 활성화할 수 없습니다."

#: src/modules/services-systemd/main.py:71
msgid "Cannot disable systemd target <code>{name!s}</code>."
msgstr "systemd 대상 <code>{name! s}</code>를 비활성화 할 수 없습니다."

#: src/modules/services-systemd/main.py:73
msgid "Cannot mask systemd unit <code>{name!s}</code>."
msgstr "시스템 유닛 <code>{name! s}</code>를 마스크할 수 없습니다."

#: src/modules/services-systemd/main.py:75
msgid ""
"Unknown systemd commands <code>{command!s}</code> and "
"<code>{suffix!s}</code> for unit {name!s}."
msgstr ""
"유닛 {name! s}에 대해 알 수 없는 시스템 명령 <code>{command! s}</code> 및 <code>{suffix! "
"s}</code>."

#: src/modules/dummypython/main.py:35
msgid "Dummy python job."
msgstr "더미 파이썬 작업."

#: src/modules/dummypython/main.py:37 src/modules/dummypython/main.py:93
#: src/modules/dummypython/main.py:94
msgid "Dummy python step {}"
msgstr "더미 파이썬 단계 {}"

#: src/modules/bootloader/main.py:43
msgid "Install bootloader."
msgstr "부트로더 설치."

#: src/modules/bootloader/main.py:614
msgid "Failed to install grub, no partitions defined in global storage"
msgstr "grub을 설치하지 못했습니다. 파티션 없음이 전역 저장소에 정의되었습니다"

#: src/modules/bootloader/main.py:782
msgid "Bootloader installation error"
msgstr "부트로더 설치 오류"

#: src/modules/bootloader/main.py:783
msgid ""
"The bootloader could not be installed. The installation command "
"<pre>{!s}</pre> returned error code {!s}."
msgstr "부트로더를 설치할 수 없습니다. <pre>{!s}</pre> 설치 명령에서  {!s} 오류 코드를 반환했습니다."

#: src/modules/localecfg/main.py:31
msgid "Configuring locales."
msgstr "로컬 구성 중."

#: src/modules/mount/main.py:42
msgid "Mounting partitions."
msgstr "파티션 마운트 중."

#: src/modules/mount/main.py:88 src/modules/mount/main.py:124
msgid "Internal error mounting zfs datasets"
msgstr "zfs 데이터세트를 마운트하는 중 내부 오류"

#: src/modules/mount/main.py:100
msgid "Failed to import zpool"
msgstr "zpool을 가져오지 못했습니다"

#: src/modules/mount/main.py:116
msgid "Failed to unlock zpool"
msgstr "zpool의 잠금을 해제하지 못했습니다"

#: src/modules/mount/main.py:133 src/modules/mount/main.py:138
msgid "Failed to set zfs mountpoint"
msgstr "zfs 마운트위치를 지정하지 못했습니다"

#: src/modules/mount/main.py:253
msgid "zfs mounting error"
msgstr "zfs 마운트하는 중 오류"

#: src/modules/plymouthcfg/main.py:27
msgid "Configure Plymouth theme"
msgstr "플리머스 테마 구성"

#: src/modules/fstab/main.py:28
msgid "Writing fstab."
msgstr "fstab 쓰기."

#: src/modules/fstab/main.py:429
msgid "No <pre>{!s}</pre> configuration is given for <pre>{!s}</pre> to use."
msgstr "<pre>{!s}</pre> 구성 없음은 <pre>{!s}</pre>을(를) 사용할 수 있도록 제공됩니다."

#: src/modules/services-openrc/main.py:29
msgid "Configure OpenRC services"
msgstr "OpenRC 서비스 구성"

#: src/modules/services-openrc/main.py:57
msgid "Cannot add service {name!s} to run-level {level!s}."
msgstr "run-level {level!s}에 {name!s} 서비스를 추가할 수 없습니다."

#: src/modules/services-openrc/main.py:59
msgid "Cannot remove service {name!s} from run-level {level!s}."
msgstr "실행-수준 {level! s}에서 서비스 {name! s}를 제거할 수 없습니다."

#: src/modules/services-openrc/main.py:61
msgid ""
"Unknown service-action <code>{arg!s}</code> for service {name!s} in run-"
"level {level!s}."
msgstr ""
"run-level {level!s}의 service {name!s}에 대해 알 수 없는 service-action "
"<code>{arg!s}</code>입니다."

#: src/modules/services-openrc/main.py:94
msgid ""
"<code>rc-update {arg!s}</code> call in chroot returned error code {num!s}."
msgstr "chroot의 <code>rc-update {arg!s}</code> 호출이 오류 코드 {num!s}를 반환 했습니다."

#: src/modules/services-openrc/main.py:101
msgid "Target runlevel does not exist"
msgstr "runlevel 대상이 존재하지 않습니다."

#: src/modules/services-openrc/main.py:102
msgid ""
"The path for runlevel {level!s} is <code>{path!s}</code>, which does not "
"exist."
msgstr "runlevel {level!s}의 경로는 존재하지 않는 {path!s}입니다."

#: src/modules/services-openrc/main.py:110
msgid "Target service does not exist"
msgstr "대상 서비스가 존재하지 않습니다."

#: src/modules/services-openrc/main.py:111
msgid ""
"The path for service {name!s} is <code>{path!s}</code>, which does not "
"exist."
msgstr "{name!s} 서비스에 대한 경로는 <code>{path!s}</code>이고, 존재하지 않습니다."

#: src/modules/dracut/main.py:27
msgid "Creating initramfs with dracut."
msgstr "dracut을 사용하여 initramfs 만들기."

#: src/modules/dracut/main.py:49
msgid "Failed to run dracut on the target"
msgstr "대상에서 dracut을 실행하지 못함"

#: src/modules/grubcfg/main.py:28
msgid "Configure GRUB."
msgstr "GRUB 구성"

#: src/modules/displaymanager/main.py:524
msgid "Cannot write KDM configuration file"
msgstr "KDM 구성 파일을 쓸 수 없습니다."

#: src/modules/displaymanager/main.py:525
msgid "KDM config file {!s} does not exist"
msgstr "KDM 구성 파일 {! s}가 없습니다"

#: src/modules/displaymanager/main.py:586
msgid "Cannot write LXDM configuration file"
msgstr "LMLDM 구성 파일을 쓸 수 없습니다."

#: src/modules/displaymanager/main.py:587
msgid "LXDM config file {!s} does not exist"
msgstr "LXDM 구성 파일 {!s}이 없습니다."

#: src/modules/displaymanager/main.py:670
msgid "Cannot write LightDM configuration file"
msgstr "LightDM 구성 파일을 쓸 수 없습니다."

#: src/modules/displaymanager/main.py:671
msgid "LightDM config file {!s} does not exist"
msgstr "LightDM 구성 파일 {!s}가 없습니다."

#: src/modules/displaymanager/main.py:745
msgid "Cannot configure LightDM"
msgstr "LightDM을 구성할 수 없습니다."

#: src/modules/displaymanager/main.py:746
msgid "No LightDM greeter installed."
msgstr "LightDM greeter가 설치되지 않았습니다."

#: src/modules/displaymanager/main.py:777
msgid "Cannot write SLIM configuration file"
msgstr "SLIM 구성 파일을 쓸 수 없음"

#: src/modules/displaymanager/main.py:778
msgid "SLIM config file {!s} does not exist"
msgstr "SLIM 구성 파일 {!s}가 없음"

#: src/modules/displaymanager/main.py:992
msgid "No display managers selected for the displaymanager module."
msgstr "displaymanager 모듈에 대해 선택된 디스플레이 관리자가 없습니다."

#: src/modules/displaymanager/main.py:993
msgid ""
"The displaymanagers list is empty or undefined in both globalstorage and "
"displaymanager.conf."
msgstr ""
"displaymanagers 목록이 비어 있거나 globalstorage 및 displaymanager.conf 모두에서 정의되지 "
"않았습니다."

#: src/modules/displaymanager/main.py:1075
msgid "Display manager configuration was incomplete"
msgstr "디스플레이 관리자 구성이 완료되지 않았습니다."

#: src/modules/initramfscfg/main.py:32
msgid "Configuring initramfs."
msgstr "initramfs 구성 중."

#: src/modules/hwclock/main.py:26
msgid "Setting hardware clock."
msgstr "하드웨어 클럭 설정 중."

#: src/modules/rawfs/main.py:26
msgid "Installing data."
msgstr "데이터 설치중."
