# SOME DESCRIPTIVE TITLE.
# Copyright (C) YEAR THE PACKAGE'S COPYRIGHT HOLDER
# This file is distributed under the same license as the PACKAGE package.
# FIRST AUTHOR <EMAIL@ADDRESS>, YEAR.
# 
# Translators:
# Źmicier Turok <nashtlumach@gmail.com>, 2022
# 
#, fuzzy
msgid ""
msgstr ""
"Project-Id-Version: PACKAGE VERSION\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2023-09-28 22:49+0200\n"
"PO-Revision-Date: 2017-08-09 10:34+0000\n"
"Last-Translator: Źmicier Turok <nashtlumach@gmail.com>, 2022\n"
"Language-Team: Belarusian (https://app.transifex.com/calamares/teams/20061/be/)\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Language: be\n"
"Plural-Forms: nplurals=4; plural=(n%10==1 && n%100!=11 ? 0 : n%10>=2 && n%10<=4 && (n%100<12 || n%100>14) ? 1 : n%10==0 || (n%10>=5 && n%10<=9) || (n%100>=11 && n%100<=14)? 2 : 3);\n"

#: src/modules/bootloader/main.py:46
msgid "Install bootloader."
msgstr "Усталяваць загрузчык."

#: src/modules/bootloader/main.py:644
msgid "Failed to install grub, no partitions defined in global storage"
msgstr ""
"Не ўдалося ўсталяваць grub, у глабальным сховішчы не вызначаны раздзелы"

#: src/modules/bootloader/main.py:899
msgid "Bootloader installation error"
msgstr "Не ўдалося ўсталяваць загрузчык"

#: src/modules/bootloader/main.py:900
msgid ""
"The bootloader could not be installed. The installation command "
"<pre>{!s}</pre> returned error code {!s}."
msgstr ""
"Не ўдалося ўсталяваць загрузчык. Загад усталявання <pre>{!s}</pre> вярнуў "
"код памылкі {!s}."

#: src/modules/displaymanager/main.py:509
msgid "Cannot write LXDM configuration file"
msgstr "Немагчыма запісаць файл канфігурацыі LXDM"

#: src/modules/displaymanager/main.py:510
msgid "LXDM config file {!s} does not exist"
msgstr "Файл канфігурацыі LXDM {!s} не існуе"

#: src/modules/displaymanager/main.py:598
msgid "Cannot write LightDM configuration file"
msgstr "Немагчыма запісаць файл канфігурацыі LightDM"

#: src/modules/displaymanager/main.py:599
msgid "LightDM config file {!s} does not exist"
msgstr "Файл канфігурацыі LightDM {!s} не існуе"

#: src/modules/displaymanager/main.py:684
msgid "Cannot configure LightDM"
msgstr "Немагчыма наладзіць LightDM"

#: src/modules/displaymanager/main.py:685
msgid "No LightDM greeter installed."
msgstr "LightDM greeter не ўсталяваны."

#: src/modules/displaymanager/main.py:716
msgid "Cannot write SLIM configuration file"
msgstr "Немагчыма запісаць файл канфігурацыі SLIM"

#: src/modules/displaymanager/main.py:717
msgid "SLIM config file {!s} does not exist"
msgstr "Файл канфігурацыі SLIM {!s} не існуе"

#: src/modules/displaymanager/main.py:935
msgid "No display managers selected for the displaymanager module."
msgstr "У модулі кіраўнікоў дысплэяў нічога не абрана."

#: src/modules/displaymanager/main.py:936
msgid ""
"The displaymanagers list is empty or undefined in both globalstorage and "
"displaymanager.conf."
msgstr ""
"Спіс кіраўнікоў дысплэяў пусты альбо не вызначаны ў both globalstorage і "
"displaymanager.conf."

#: src/modules/displaymanager/main.py:1023
msgid "Display manager configuration was incomplete"
msgstr "Наладжванне кіраўніка дысплэяў не завершана"

#: src/modules/dracut/main.py:29
msgid "Creating initramfs with dracut."
msgstr "Стварэнне initramfs з dracut."

#: src/modules/dracut/main.py:63
msgid "Failed to run dracut"
msgstr ""

#: src/modules/dracut/main.py:64
#, python-brace-format
msgid "Dracut failed to run on the target with return code: {return_code}"
msgstr ""

#: src/modules/dummypython/main.py:35
msgid "Dummy python job."
msgstr "Задача Dummy python."

#: src/modules/dummypython/main.py:37 src/modules/dummypython/main.py:93
#: src/modules/dummypython/main.py:94
msgid "Dummy python step {}"
msgstr "Крок Dummy python {}"

#: src/modules/fstab/main.py:28
msgid "Writing fstab."
msgstr "Запіс fstab."

#: src/modules/fstab/main.py:377 src/modules/fstab/main.py:383
#: src/modules/fstab/main.py:411 src/modules/initcpiocfg/main.py:256
#: src/modules/initcpiocfg/main.py:260 src/modules/initramfscfg/main.py:85
#: src/modules/initramfscfg/main.py:89 src/modules/localecfg/main.py:140
#: src/modules/mount/main.py:329 src/modules/networkcfg/main.py:105
#: src/modules/openrcdmcryptcfg/main.py:72
#: src/modules/openrcdmcryptcfg/main.py:76 src/modules/rawfs/main.py:164
msgid "Configuration Error"
msgstr "Памылка канфігурацыі"

#: src/modules/fstab/main.py:378 src/modules/initramfscfg/main.py:86
#: src/modules/mount/main.py:330 src/modules/openrcdmcryptcfg/main.py:73
#: src/modules/rawfs/main.py:165
msgid "No partitions are defined for <pre>{!s}</pre> to use."
msgstr "Раздзелы для <pre>{!s}</pre> не вызначаныя."

#: src/modules/fstab/main.py:384 src/modules/initramfscfg/main.py:90
#: src/modules/localecfg/main.py:141 src/modules/networkcfg/main.py:106
#: src/modules/openrcdmcryptcfg/main.py:77
msgid "No root mount point is given for <pre>{!s}</pre> to use."
msgstr "Каранёвы пункт мантавання для<pre>{!s}</pre> не пададзены."

#: src/modules/fstab/main.py:412
msgid "No <pre>{!s}</pre> configuration is given for <pre>{!s}</pre> to use."
msgstr ""
"Не пададзена канфігурацыі <pre>{!s}</pre> для выкарыстання <pre>{!s}</pre>."

#: src/modules/grubcfg/main.py:29
msgid "Configure GRUB."
msgstr "Наладжванне GRUB."

#: src/modules/hwclock/main.py:26
msgid "Setting hardware clock."
msgstr "Наладжванне апаратнага гадзінніка."

#: src/modules/initcpiocfg/main.py:27
msgid "Configuring mkinitcpio."
msgstr "Наладжванне mkinitcpio."

#: src/modules/initcpiocfg/main.py:257
msgid "No partitions are defined for <pre>initcpiocfg</pre>."
msgstr ""

#: src/modules/initcpiocfg/main.py:261
msgid "No root mount point for <pre>initcpiocfg</pre>."
msgstr ""

#: src/modules/initramfscfg/main.py:32
msgid "Configuring initramfs."
msgstr "Наладжванне initramfs."

#: src/modules/localecfg/main.py:31
msgid "Configuring locales."
msgstr "Наладжванне лакаляў."

#: src/modules/mkinitfs/main.py:27
msgid "Creating initramfs with mkinitfs."
msgstr "Стварэнне initramfs праз mkinitfs."

#: src/modules/mkinitfs/main.py:49
msgid "Failed to run mkinitfs on the target"
msgstr "Не ўдалося запусціць mkinitfs у пункце прызначэння"

#: src/modules/mkinitfs/main.py:50
msgid "The exit code was {}"
msgstr "Код выхаду {}"

#: src/modules/mount/main.py:43
msgid "Mounting partitions."
msgstr "Мантаванне раздзелаў."

#: src/modules/mount/main.py:164 src/modules/mount/main.py:200
msgid "Internal error mounting zfs datasets"
msgstr "Унутраная памылка мантавання набораў даных zfs"

#: src/modules/mount/main.py:176
msgid "Failed to import zpool"
msgstr "Не ўдалося імпартаваць zpool"

#: src/modules/mount/main.py:192
msgid "Failed to unlock zpool"
msgstr "Не ўдалося разблакаваць zpool"

#: src/modules/mount/main.py:209 src/modules/mount/main.py:214
msgid "Failed to set zfs mountpoint"
msgstr "Не ўдалося вызначыць пункт мантавання zfs"

#: src/modules/mount/main.py:365
msgid "zfs mounting error"
msgstr "памылка мантавання zfs"

#: src/modules/networkcfg/main.py:29
msgid "Saving network configuration."
msgstr "Захаванне сеткавай канфігурацыі."

#: src/modules/openrcdmcryptcfg/main.py:26
msgid "Configuring OpenRC dmcrypt service."
msgstr "Наладжванне OpenRC dmcrypt."

#: src/modules/packages/main.py:54 src/modules/packages/main.py:65
#: src/modules/packages/main.py:75
msgid "Install packages."
msgstr "Усталяваць пакункі."

#: src/modules/packages/main.py:63
#, python-format
msgid "Processing packages (%(count)d / %(total)d)"
msgstr "Апрацоўка пакункаў (%(count)d / %(total)d)"

#: src/modules/packages/main.py:68
#, python-format
msgid "Installing one package."
msgid_plural "Installing %(num)d packages."
msgstr[0] "Усталяванне аднаго пакунка."
msgstr[1] "Усталяванне %(num)d пакункаў."
msgstr[2] "Усталяванне %(num)d пакункаў."
msgstr[3] "Усталяванне %(num)d пакункаў."

#: src/modules/packages/main.py:71
#, python-format
msgid "Removing one package."
msgid_plural "Removing %(num)d packages."
msgstr[0] "Выдаленне аднаго пакунка."
msgstr[1] "Выдаленне %(num)d пакункаў."
msgstr[2] "Выдаленне %(num)d пакункаў."
msgstr[3] "Выдаленне %(num)d пакункаў."

#: src/modules/packages/main.py:740 src/modules/packages/main.py:752
#: src/modules/packages/main.py:780
msgid "Package Manager error"
msgstr "Памылка кіраўніка пакункаў"

#: src/modules/packages/main.py:741
msgid ""
"The package manager could not prepare updates. The command <pre>{!s}</pre> "
"returned error code {!s}."
msgstr ""
"Кіраўніку пакункаў не ўдалося падрыхтаваць абнаўленні. Загад <pre>{!s}</pre>"
" вярнуў код памылкі {!s}."

#: src/modules/packages/main.py:753
msgid ""
"The package manager could not update the system. The command <pre>{!s}</pre>"
" returned error code {!s}."
msgstr ""
"Кіраўніку пакункаў не ўдалося абнавіць сістэму. Загад <pre>{!s}</pre> вярнуў"
" код памылкі {!s}."

#: src/modules/packages/main.py:781
msgid ""
"The package manager could not make changes to the installed system. The "
"command <pre>{!s}</pre> returned error code {!s}."
msgstr ""
"Кіраўніку пакункаў не ўдалося ўнесці змены ва ўсталяваную сістэму. Загад "
"<pre>{!s}</pre> вярнуў код памылкі {!s}."

#: src/modules/plymouthcfg/main.py:27
msgid "Configure Plymouth theme"
msgstr "Наладжванне тэмы Plymouth"

#: src/modules/rawfs/main.py:26
msgid "Installing data."
msgstr "Усталяванне даных."

#: src/modules/services-openrc/main.py:29
msgid "Configure OpenRC services"
msgstr "Наладжванне службаў OpenRC"

#: src/modules/services-openrc/main.py:57
msgid "Cannot add service {name!s} to run-level {level!s}."
msgstr "Не ўдалося дадаць службу {name!s} на ўзровень запуску {level!s}."

#: src/modules/services-openrc/main.py:59
msgid "Cannot remove service {name!s} from run-level {level!s}."
msgstr "Не ўдалося выдаліць службу {name!s} з узроўню запуску {level!s}."

#: src/modules/services-openrc/main.py:61
msgid ""
"Unknown service-action <code>{arg!s}</code> for service {name!s} in run-"
"level {level!s}."
msgstr ""
"Невядомае дзеянне <code>{arg!s}</code> для службы {name!s} на ўзроўні "
"запуску {level!s}."

#: src/modules/services-openrc/main.py:93
msgid "Cannot modify service"
msgstr "Немагчыма наладзіць службу"

#: src/modules/services-openrc/main.py:94
msgid ""
"<code>rc-update {arg!s}</code> call in chroot returned error code {num!s}."
msgstr ""
"<code>rc-update {arg!s}</code> пад chroot вярнуўся з кодам памылкі {num!s}."

#: src/modules/services-openrc/main.py:101
msgid "Target runlevel does not exist"
msgstr "Мэтавы ўзровень запуску не існуе"

#: src/modules/services-openrc/main.py:102
msgid ""
"The path for runlevel {level!s} is <code>{path!s}</code>, which does not "
"exist."
msgstr "Шлях <code>{path!s}</code> да ўзроўню запуску {level!s} не існуе."

#: src/modules/services-openrc/main.py:110
msgid "Target service does not exist"
msgstr "Мэтавая служба не існуе"

#: src/modules/services-openrc/main.py:111
msgid ""
"The path for service {name!s} is <code>{path!s}</code>, which does not "
"exist."
msgstr "Шлях <code>{path!s}</code> да службы {level!s} не існуе."

#: src/modules/services-systemd/main.py:26
msgid "Configure systemd units"
msgstr ""

#: src/modules/services-systemd/main.py:64
msgid "Cannot modify unit"
msgstr ""

#: src/modules/services-systemd/main.py:65
msgid ""
"<code>systemctl {_action!s}</code> call in chroot returned error code "
"{_exit_code!s}."
msgstr ""

#: src/modules/services-systemd/main.py:66
msgid "Cannot {_action!s} systemd unit <code>{_name!s}</code>."
msgstr ""

#: src/modules/unpackfs/main.py:34
msgid "Filling up filesystems."
msgstr "Запаўненне файлавых сістэм."

#: src/modules/unpackfs/main.py:254
msgid "rsync failed with error code {}."
msgstr "памылка rsync з кодам {}."

#: src/modules/unpackfs/main.py:299
msgid "Unpacking image {}/{}, file {}/{}"
msgstr "Распакоўванне вобраза {}/{}, файл {}/{}"

#: src/modules/unpackfs/main.py:314
msgid "Starting to unpack {}"
msgstr "Запуск распакоўвання {}"

#: src/modules/unpackfs/main.py:323 src/modules/unpackfs/main.py:467
msgid "Failed to unpack image \"{}\""
msgstr "Не ўдалося распакаваць вобраз \"{}\""

#: src/modules/unpackfs/main.py:430
msgid "No mount point for root partition"
msgstr "Для каранёвага раздзела няма пункта мантавання"

#: src/modules/unpackfs/main.py:431
msgid "globalstorage does not contain a \"rootMountPoint\" key."
msgstr "globalstorage не змяшчае ключа \"rootMountPoint\"."

#: src/modules/unpackfs/main.py:434
msgid "Bad mount point for root partition"
msgstr "Хібны пункт мантавання для каранёвага раздзела"

#: src/modules/unpackfs/main.py:435
msgid "rootMountPoint is \"{}\", which does not exist."
msgstr "rootMountPoint \"{}\" не існуе."

#: src/modules/unpackfs/main.py:439 src/modules/unpackfs/main.py:455
#: src/modules/unpackfs/main.py:459 src/modules/unpackfs/main.py:465
#: src/modules/unpackfs/main.py:480
msgid "Bad unpackfs configuration"
msgstr "Хібная канфігурацыя unpackfs"

#: src/modules/unpackfs/main.py:440
msgid "There is no configuration information."
msgstr "Няма звестак канфігурацыі."

#: src/modules/unpackfs/main.py:456
msgid "The filesystem for \"{}\" ({}) is not supported by your current kernel"
msgstr "Файлавая сістэма для \"{}\" ({}) не падтрымліваецца вашым бягучым ядром"

#: src/modules/unpackfs/main.py:460
msgid "The source filesystem \"{}\" does not exist"
msgstr "Зыходная файлавая сістэма \"{}\" не існуе"

#: src/modules/unpackfs/main.py:466
msgid ""
"Failed to find unsquashfs, make sure you have the squashfs-tools package "
"installed."
msgstr ""
"Не ўдалося знайсці unsquashfs, праверце ці ўсталяваны ў вас пакунак "
"squashfs-tools."

#: src/modules/unpackfs/main.py:481
msgid "The destination \"{}\" in the target system is not a directory"
msgstr "Пункт прызначэння \"{}\" у мэтавай сістэме не ёсць каталогам"

#: src/modules/zfshostid/main.py:27
msgid "Copying zfs generated hostid."
msgstr ""
