# SOME DESCRIPTIVE TITLE.
# Copyright (C) YEAR THE PACKAGE'S COPYRIGHT HOLDER
# This file is distributed under the same license as the PACKAGE package.
# FIRST AUTHOR <EMAIL@ADDRESS>, YEAR.
# 
# Translators:
# pavelrz, 2017
# LiberteCzech <martin.kriz.czech@gmail.com>, 2020
# Pavel Borecki <pavel.borecki@gmail.com>, 2022
# 
#, fuzzy
msgid ""
msgstr ""
"Project-Id-Version: PACKAGE VERSION\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2022-05-27 11:18+0200\n"
"PO-Revision-Date: 2017-08-09 10:34+0000\n"
"Last-Translator: Pavel Borecki <pavel.borecki@gmail.com>, 2022\n"
"Language-Team: Czech (Czech Republic) (https://www.transifex.com/calamares/teams/20061/cs_CZ/)\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Language: cs_CZ\n"
"Plural-Forms: nplurals=4; plural=(n == 1 && n % 1 == 0) ? 0 : (n >= 2 && n <= 4 && n % 1 == 0) ? 1: (n % 1 != 0 ) ? 2 : 3;\n"

#: src/modules/packages/main.py:54 src/modules/packages/main.py:65
#: src/modules/packages/main.py:75
msgid "Install packages."
msgstr "Nainstalovat balíčky."

#: src/modules/packages/main.py:63
#, python-format
msgid "Processing packages (%(count)d / %(total)d)"
msgstr "Zpracovávání balíčků (%(count)d / %(total)d)"

#: src/modules/packages/main.py:68
#, python-format
msgid "Installing one package."
msgid_plural "Installing %(num)d packages."
msgstr[0] "Je instalován jeden balíček."
msgstr[1] "Jsou instalovány %(num)d balíčky."
msgstr[2] "Je instalováno %(num)d balíčků."
msgstr[3] "Je instalováno %(num)d balíčků."

#: src/modules/packages/main.py:71
#, python-format
msgid "Removing one package."
msgid_plural "Removing %(num)d packages."
msgstr[0] "Odebírá se jeden balíček."
msgstr[1] "Odebírají se %(num)d balíčky."
msgstr[2] "Odebírá se %(num)d balíčků."
msgstr[3] "Odebírá se %(num)d balíčků."

#: src/modules/packages/main.py:725 src/modules/packages/main.py:737
#: src/modules/packages/main.py:765
msgid "Package Manager error"
msgstr "Chyba nástroje pro správu balíčků"

#: src/modules/packages/main.py:726
msgid ""
"The package manager could not prepare updates. The command <pre>{!s}</pre> "
"returned error code {!s}."
msgstr ""
"Nástroji pro správu balíčků se nepodařilo připravit aktualizace. Příkaz "
"<pre>{!s}</pre> vrátil chybový kód {!s}."

#: src/modules/packages/main.py:738
msgid ""
"The package manager could not update the system. The command <pre>{!s}</pre>"
" returned error code {!s}."
msgstr ""
"Nástroji pro správu balíčků se nepodařilo aktualizovat systém. Příkaz "
"<pre>{!s}</pre> vrátil chybový kód {!s}."

#: src/modules/packages/main.py:766
msgid ""
"The package manager could not make changes to the installed system. The "
"command <pre>{!s}</pre> returned error code {!s}."
msgstr ""
"Nástroji pro správu balíčků se nepodařilo udělat změny v instalovaném "
"systému. Příkaz <pre>{!s}</pre> vrátil chybový kód {!s}."

#: src/modules/networkcfg/main.py:29
msgid "Saving network configuration."
msgstr "Ukládání nastavení sítě."

#: src/modules/networkcfg/main.py:105 src/modules/initcpiocfg/main.py:235
#: src/modules/initcpiocfg/main.py:239 src/modules/openrcdmcryptcfg/main.py:72
#: src/modules/openrcdmcryptcfg/main.py:76 src/modules/localecfg/main.py:140
#: src/modules/mount/main.py:229 src/modules/fstab/main.py:394
#: src/modules/fstab/main.py:400 src/modules/fstab/main.py:428
#: src/modules/initramfscfg/main.py:85 src/modules/initramfscfg/main.py:89
#: src/modules/rawfs/main.py:164
msgid "Configuration Error"
msgstr "Chyba nastavení"

#: src/modules/networkcfg/main.py:106 src/modules/initcpiocfg/main.py:240
#: src/modules/openrcdmcryptcfg/main.py:77 src/modules/localecfg/main.py:141
#: src/modules/fstab/main.py:401 src/modules/initramfscfg/main.py:90
msgid "No root mount point is given for <pre>{!s}</pre> to use."
msgstr "Pro <pre>{!s}</pre> není zadán žádný přípojný bod."

#: src/modules/initcpiocfg/main.py:28
msgid "Configuring mkinitcpio."
msgstr "Nastavování mkinitcpio."

#: src/modules/initcpiocfg/main.py:236 src/modules/openrcdmcryptcfg/main.py:73
#: src/modules/mount/main.py:230 src/modules/fstab/main.py:395
#: src/modules/initramfscfg/main.py:86 src/modules/rawfs/main.py:165
msgid "No partitions are defined for <pre>{!s}</pre> to use."
msgstr "Pro <pre>{!s}</pre> nejsou zadány žádné oddíly."

#: src/modules/mkinitfs/main.py:27
msgid "Creating initramfs with mkinitfs."
msgstr "Vytváření initramfs nástrojem mkinitfs."

#: src/modules/mkinitfs/main.py:49
msgid "Failed to run mkinitfs on the target"
msgstr "Na cíli se nepodařilo spustit mkinitfs"

#: src/modules/mkinitfs/main.py:50 src/modules/dracut/main.py:50
msgid "The exit code was {}"
msgstr "Návratový kód byl {}"

#: src/modules/openrcdmcryptcfg/main.py:26
msgid "Configuring OpenRC dmcrypt service."
msgstr "Nastavování služby OpenRC dmcrypt."

#: src/modules/unpackfs/main.py:34
msgid "Filling up filesystems."
msgstr "Naplňování souborových systémů."

#: src/modules/unpackfs/main.py:254
msgid "rsync failed with error code {}."
msgstr "rsync se nezdařilo s chybových kódem {}."

#: src/modules/unpackfs/main.py:299
msgid "Unpacking image {}/{}, file {}/{}"
msgstr "Rozbalování obrazu {}/{}, soubor {}/{}"

#: src/modules/unpackfs/main.py:314
msgid "Starting to unpack {}"
msgstr "Zahajování rozbalení {}"

#: src/modules/unpackfs/main.py:323 src/modules/unpackfs/main.py:467
msgid "Failed to unpack image \"{}\""
msgstr "Nepodařilo se rozbalit obraz „{}“"

#: src/modules/unpackfs/main.py:430
msgid "No mount point for root partition"
msgstr "Žádný přípojný bot pro kořenový oddíl"

#: src/modules/unpackfs/main.py:431
msgid "globalstorage does not contain a \"rootMountPoint\" key."
msgstr "globalstorage neobsahuje klíč „rootMountPoint“."

#: src/modules/unpackfs/main.py:434
msgid "Bad mount point for root partition"
msgstr "Chybný přípojný bod pro kořenový oddíl"

#: src/modules/unpackfs/main.py:435
msgid "rootMountPoint is \"{}\", which does not exist."
msgstr "rootMountPoint je „{}“, což neexistuje."

#: src/modules/unpackfs/main.py:439 src/modules/unpackfs/main.py:455
#: src/modules/unpackfs/main.py:459 src/modules/unpackfs/main.py:465
#: src/modules/unpackfs/main.py:480
msgid "Bad unpackfs configuration"
msgstr "Chybné nastavení unpackfs"

#: src/modules/unpackfs/main.py:440
msgid "There is no configuration information."
msgstr "Není zde žádná informace o nastavení."

#: src/modules/unpackfs/main.py:456
msgid "The filesystem for \"{}\" ({}) is not supported by your current kernel"
msgstr ""
"Souborový systém „{}“ ({}) není jádrem systému, které právě používáte, "
"podporován"

#: src/modules/unpackfs/main.py:460
msgid "The source filesystem \"{}\" does not exist"
msgstr "Zdrojový souborový systém „{}“ neexistuje"

#: src/modules/unpackfs/main.py:466
msgid ""
"Failed to find unsquashfs, make sure you have the squashfs-tools package "
"installed."
msgstr ""
"Nepodařilo se nalézt nástroj unsquashfs – ověřte, že je nainstalovaný "
"balíček squashfs-tools."

#: src/modules/unpackfs/main.py:481
msgid "The destination \"{}\" in the target system is not a directory"
msgstr "Cíl „{}“ v cílovém systému není složka"

#: src/modules/services-systemd/main.py:26
msgid "Configure systemd services"
msgstr "Nastavit služby systemd"

#: src/modules/services-systemd/main.py:59
#: src/modules/services-openrc/main.py:93
msgid "Cannot modify service"
msgstr "Službu se nedaří upravit"

#: src/modules/services-systemd/main.py:60
msgid ""
"<code>systemctl {arg!s}</code> call in chroot returned error code {num!s}."
msgstr ""
"Volání <code>systemctl {arg!s}</code> v chroot vrátilo chybový kód {num!s}."

#: src/modules/services-systemd/main.py:63
#: src/modules/services-systemd/main.py:69
msgid "Cannot enable systemd service <code>{name!s}</code>."
msgstr "Nedaří se zapnout systemd službu <code>{name!s}</code>."

#: src/modules/services-systemd/main.py:65
msgid "Cannot enable systemd target <code>{name!s}</code>."
msgstr "Nedaří se zapnout systemd službu <code>{name!s}</code>."

#: src/modules/services-systemd/main.py:67
msgid "Cannot enable systemd timer <code>{name!s}</code>."
msgstr "Nedaří se zapnout systemd časovač <code>{name!s}</code>."

#: src/modules/services-systemd/main.py:71
msgid "Cannot disable systemd target <code>{name!s}</code>."
msgstr "Nedaří se vypnout systemd cíl <code>{name!s}</code>."

#: src/modules/services-systemd/main.py:73
msgid "Cannot mask systemd unit <code>{name!s}</code>."
msgstr "Nedaří se maskovat systemd jednotku <code>{name!s}</code>."

#: src/modules/services-systemd/main.py:75
msgid ""
"Unknown systemd commands <code>{command!s}</code> and "
"<code>{suffix!s}</code> for unit {name!s}."
msgstr ""
"Neznámé systemd příkazy <code>{command!s}</code> a <code>{suffix!s}</code> "
"pro jednotku {name!s}."

#: src/modules/dummypython/main.py:35
msgid "Dummy python job."
msgstr "Testovací úloha python."

#: src/modules/dummypython/main.py:37 src/modules/dummypython/main.py:93
#: src/modules/dummypython/main.py:94
msgid "Dummy python step {}"
msgstr "Testovací krok {} python."

#: src/modules/bootloader/main.py:43
msgid "Install bootloader."
msgstr "Instalace zavaděče systému."

#: src/modules/bootloader/main.py:614
msgid "Failed to install grub, no partitions defined in global storage"
msgstr ""
"Nepodařilo se nainstalovat zavaděč grub – v globálním úložišti nejsou "
"definovány žádné oddíly"

#: src/modules/bootloader/main.py:782
msgid "Bootloader installation error"
msgstr "Chyba při instalaci zavaděče systému"

#: src/modules/bootloader/main.py:783
msgid ""
"The bootloader could not be installed. The installation command "
"<pre>{!s}</pre> returned error code {!s}."
msgstr ""
"Zavaděč systému se nepodařilo nainstalovat. Instalační příkaz <pre>{!s} "
"vrátil chybový kód {!s}."

#: src/modules/localecfg/main.py:31
msgid "Configuring locales."
msgstr "Nastavování místních a jazykových nastavení."

#: src/modules/mount/main.py:42
msgid "Mounting partitions."
msgstr "Připojování oddílů."

#: src/modules/mount/main.py:88 src/modules/mount/main.py:124
msgid "Internal error mounting zfs datasets"
msgstr "Vnitřní chyba při připojování zfs datových sad"

#: src/modules/mount/main.py:100
msgid "Failed to import zpool"
msgstr "Nepodařilo se naimportovat zfs fond"

#: src/modules/mount/main.py:116
msgid "Failed to unlock zpool"
msgstr "Nepodařilo se odemknout zfs fond"

#: src/modules/mount/main.py:133 src/modules/mount/main.py:138
msgid "Failed to set zfs mountpoint"
msgstr "Nepodařilo se nastavit zfs přípojný bod"

#: src/modules/mount/main.py:253
msgid "zfs mounting error"
msgstr "Chyba při připojování zfs"

#: src/modules/plymouthcfg/main.py:27
msgid "Configure Plymouth theme"
msgstr "Nastavit téma vzhledu pro Plymouth"

#: src/modules/fstab/main.py:28
msgid "Writing fstab."
msgstr "Zapisování fstab."

#: src/modules/fstab/main.py:429
msgid "No <pre>{!s}</pre> configuration is given for <pre>{!s}</pre> to use."
msgstr ""
"Pro <pre>{!s}</pre> není zadáno žádné nastavení <pre>{!s}</pre>, které "
"použít. "

#: src/modules/services-openrc/main.py:29
msgid "Configure OpenRC services"
msgstr "Nastavit OpenRC služby"

#: src/modules/services-openrc/main.py:57
msgid "Cannot add service {name!s} to run-level {level!s}."
msgstr ""
"Nedaří se přidat službu {name!s} do úrovně chodu (runlevel) {level!s}."

#: src/modules/services-openrc/main.py:59
msgid "Cannot remove service {name!s} from run-level {level!s}."
msgstr ""
"Nedaří se odebrat službu {name!s} z úrovně chodu (runlevel) {level!s}."

#: src/modules/services-openrc/main.py:61
msgid ""
"Unknown service-action <code>{arg!s}</code> for service {name!s} in run-"
"level {level!s}."
msgstr ""
"Neznámá akce služby <code>{arg!s}</code> pro službu {name!s} v úrovni chodu "
"(runlevel) {level!s}."

#: src/modules/services-openrc/main.py:94
msgid ""
"<code>rc-update {arg!s}</code> call in chroot returned error code {num!s}."
msgstr ""
"<code>rc-update {arg!s}</code> volání v chroot vrátilo kód chyby {num!s}."

#: src/modules/services-openrc/main.py:101
msgid "Target runlevel does not exist"
msgstr "Cílová úroveň chodu (runlevel) neexistuje"

#: src/modules/services-openrc/main.py:102
msgid ""
"The path for runlevel {level!s} is <code>{path!s}</code>, which does not "
"exist."
msgstr ""
"Popis umístění pro úroveň chodu (runlevel) {level!s} je "
"<code>{path!s}</code>, keterá neexistuje."

#: src/modules/services-openrc/main.py:110
msgid "Target service does not exist"
msgstr "Cílová služba neexistuje"

#: src/modules/services-openrc/main.py:111
msgid ""
"The path for service {name!s} is <code>{path!s}</code>, which does not "
"exist."
msgstr ""
"Popis umístění pro službu {name!s} je <code>{path!s}</code>, která "
"neexistuje."

#: src/modules/dracut/main.py:27
msgid "Creating initramfs with dracut."
msgstr "Vytváření initramfs s dracut."

#: src/modules/dracut/main.py:49
msgid "Failed to run dracut on the target"
msgstr "Na cíli se nepodařilo spustit dracut"

#: src/modules/grubcfg/main.py:28
msgid "Configure GRUB."
msgstr "Nastavování zavaděče GRUB."

#: src/modules/displaymanager/main.py:524
msgid "Cannot write KDM configuration file"
msgstr "Nedaří se zapsat soubor s nastaveními pro KDM"

#: src/modules/displaymanager/main.py:525
msgid "KDM config file {!s} does not exist"
msgstr "Soubor s nastaveními pro KDM {!s} neexistuje"

#: src/modules/displaymanager/main.py:586
msgid "Cannot write LXDM configuration file"
msgstr "Nedaří se zapsat soubor s nastaveními pro LXDM"

#: src/modules/displaymanager/main.py:587
msgid "LXDM config file {!s} does not exist"
msgstr "Soubor s nastaveními pro LXDM {!s} neexistuje"

#: src/modules/displaymanager/main.py:670
msgid "Cannot write LightDM configuration file"
msgstr "Nedaří se zapsat soubor s nastaveními pro LightDM"

#: src/modules/displaymanager/main.py:671
msgid "LightDM config file {!s} does not exist"
msgstr "Soubor s nastaveními pro LightDM {!s} neexistuje"

#: src/modules/displaymanager/main.py:745
msgid "Cannot configure LightDM"
msgstr "Nedaří se nastavit LightDM"

#: src/modules/displaymanager/main.py:746
msgid "No LightDM greeter installed."
msgstr "Není nainstalovaný žádný LightDM přivítač"

#: src/modules/displaymanager/main.py:777
msgid "Cannot write SLIM configuration file"
msgstr "Nedaří se zapsat soubor s nastaveními pro SLIM"

#: src/modules/displaymanager/main.py:778
msgid "SLIM config file {!s} does not exist"
msgstr "Soubor s nastaveními pro SLIM {!s} neexistuje"

#: src/modules/displaymanager/main.py:992
msgid "No display managers selected for the displaymanager module."
msgstr "Pro modul správce sezení nejsou vybrány žádní správci sezení."

#: src/modules/displaymanager/main.py:993
msgid ""
"The displaymanagers list is empty or undefined in both globalstorage and "
"displaymanager.conf."
msgstr ""
"Seznam správců displejů je prázdný nebo není definován v jak globalstorage, "
"tak v displaymanager.conf."

#: src/modules/displaymanager/main.py:1075
msgid "Display manager configuration was incomplete"
msgstr "Nastavení správce displeje nebylo úplné"

#: src/modules/initramfscfg/main.py:32
msgid "Configuring initramfs."
msgstr "Nastavování initramfs."

#: src/modules/hwclock/main.py:26
msgid "Setting hardware clock."
msgstr "Nastavování hardwarových hodin."

#: src/modules/rawfs/main.py:26
msgid "Installing data."
msgstr "Instalace dat."
