# SOME DESCRIPTIVE TITLE.
# Copyright (C) YEAR THE PACKAGE'S COPYRIGHT HOLDER
# This file is distributed under the same license as the PACKAGE package.
# FIRST AUTHOR <EMAIL@ADDRESS>, YEAR.
# 
# Translators:
# Nuno Amorim <inovaty@gmail.com>, 2018
# Ricardo Simões <xmcorporation@gmail.com>, 2020
# Hugo Carvalho <hugokarvalho@hotmail.com>, 2023
# 
#, fuzzy
msgid ""
msgstr ""
"Project-Id-Version: PACKAGE VERSION\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2023-09-28 22:49+0200\n"
"PO-Revision-Date: 2017-08-09 10:34+0000\n"
"Last-Translator: Hugo Carvalho <hugokarvalho@hotmail.com>, 2023\n"
"Language-Team: Portuguese (Portugal) (https://app.transifex.com/calamares/teams/20061/pt_PT/)\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Language: pt_PT\n"
"Plural-Forms: nplurals=3; plural=(n == 0 || n == 1) ? 0 : n != 0 && n % 1000000 == 0 ? 1 : 2;\n"

#: src/modules/bootloader/main.py:46
msgid "Install bootloader."
msgstr "Instalar o carregador de arranque."

#: src/modules/bootloader/main.py:644
msgid "Failed to install grub, no partitions defined in global storage"
msgstr ""
"Falha ao instalar o grub, sem partições definidas no armazenamento global"

#: src/modules/bootloader/main.py:899
msgid "Bootloader installation error"
msgstr "Erro de instalação do carregador de arranque"

#: src/modules/bootloader/main.py:900
msgid ""
"The bootloader could not be installed. The installation command "
"<pre>{!s}</pre> returned error code {!s}."
msgstr ""
"Não foi possível instalar o carregador de arranque. O comando de instalação "
"<pre>{!s}</pre> apresentou o código de erro {!s}."

#: src/modules/displaymanager/main.py:509
msgid "Cannot write LXDM configuration file"
msgstr "Não é possível gravar o ficheiro de configuração LXDM"

#: src/modules/displaymanager/main.py:510
msgid "LXDM config file {!s} does not exist"
msgstr "O ficheiro de configuração do LXDM {!s} não existe"

#: src/modules/displaymanager/main.py:598
msgid "Cannot write LightDM configuration file"
msgstr "Não é possível gravar o ficheiro de configuração LightDM"

#: src/modules/displaymanager/main.py:599
msgid "LightDM config file {!s} does not exist"
msgstr "O ficheiro de configuração do LightDM {!s} não existe"

#: src/modules/displaymanager/main.py:684
msgid "Cannot configure LightDM"
msgstr "Não é possível configurar o LightDM"

#: src/modules/displaymanager/main.py:685
msgid "No LightDM greeter installed."
msgstr "Nenhum ecrã de boas-vindas LightDM instalado."

#: src/modules/displaymanager/main.py:716
msgid "Cannot write SLIM configuration file"
msgstr "Não é possível gravar o ficheiro de configuração SLIM"

#: src/modules/displaymanager/main.py:717
msgid "SLIM config file {!s} does not exist"
msgstr "O ficheiro de configuração do SLIM {!s} não existe"

#: src/modules/displaymanager/main.py:935
msgid "No display managers selected for the displaymanager module."
msgstr ""
"Nenhum gestor de exibição selecionado para o módulo de gestor de exibição."

#: src/modules/displaymanager/main.py:936
msgid ""
"The displaymanagers list is empty or undefined in both globalstorage and "
"displaymanager.conf."
msgstr ""
"A lista de gestores de visualização está vazia ou indefinida tanto no "
"globalstorage como no displaymanager.conf."

#: src/modules/displaymanager/main.py:1023
msgid "Display manager configuration was incomplete"
msgstr "A configuração do gestor de exibição estava incompleta"

#: src/modules/dracut/main.py:29
msgid "Creating initramfs with dracut."
msgstr "Criando o initramfs com o dracut."

#: src/modules/dracut/main.py:63
msgid "Failed to run dracut"
msgstr "Falha ao executar o dracut"

#: src/modules/dracut/main.py:64
#, python-brace-format
msgid "Dracut failed to run on the target with return code: {return_code}"
msgstr ""
"Não foi possível executar o dracut no alvo com o código de retorno: "
"{return_code}"

#: src/modules/dummypython/main.py:35
msgid "Dummy python job."
msgstr "Tarefa Dummy python."

#: src/modules/dummypython/main.py:37 src/modules/dummypython/main.py:93
#: src/modules/dummypython/main.py:94
msgid "Dummy python step {}"
msgstr "Passo Dummy python {}"

#: src/modules/fstab/main.py:28
msgid "Writing fstab."
msgstr "A escrever o fstab."

#: src/modules/fstab/main.py:377 src/modules/fstab/main.py:383
#: src/modules/fstab/main.py:411 src/modules/initcpiocfg/main.py:256
#: src/modules/initcpiocfg/main.py:260 src/modules/initramfscfg/main.py:85
#: src/modules/initramfscfg/main.py:89 src/modules/localecfg/main.py:140
#: src/modules/mount/main.py:329 src/modules/networkcfg/main.py:105
#: src/modules/openrcdmcryptcfg/main.py:72
#: src/modules/openrcdmcryptcfg/main.py:76 src/modules/rawfs/main.py:164
msgid "Configuration Error"
msgstr "Erro de configuração"

#: src/modules/fstab/main.py:378 src/modules/initramfscfg/main.py:86
#: src/modules/mount/main.py:330 src/modules/openrcdmcryptcfg/main.py:73
#: src/modules/rawfs/main.py:165
msgid "No partitions are defined for <pre>{!s}</pre> to use."
msgstr "Nenhuma partição está definida para <pre>{!s}</pre> usar."

#: src/modules/fstab/main.py:384 src/modules/initramfscfg/main.py:90
#: src/modules/localecfg/main.py:141 src/modules/networkcfg/main.py:106
#: src/modules/openrcdmcryptcfg/main.py:77
msgid "No root mount point is given for <pre>{!s}</pre> to use."
msgstr "Nenhum ponto de montagem root é fornecido para <pre>{!s}</pre> usar."

#: src/modules/fstab/main.py:412
msgid "No <pre>{!s}</pre> configuration is given for <pre>{!s}</pre> to use."
msgstr ""
"Não é dada nenhuma configuração <pre>{!s}</pre> para <pre>{!s}</pre> "
"utilizar."

#: src/modules/grubcfg/main.py:29
msgid "Configure GRUB."
msgstr "Configurar o GRUB."

#: src/modules/hwclock/main.py:26
msgid "Setting hardware clock."
msgstr "A definir o relógio do hardware."

#: src/modules/initcpiocfg/main.py:27
msgid "Configuring mkinitcpio."
msgstr "A configurar o mkintcpio."

#: src/modules/initcpiocfg/main.py:257
msgid "No partitions are defined for <pre>initcpiocfg</pre>."
msgstr "Nenhuma partição está definida para <pre>initcpiocfg</pre>."

#: src/modules/initcpiocfg/main.py:261
msgid "No root mount point for <pre>initcpiocfg</pre>."
msgstr "Nenhum ponto de montagem root para <pre>initcpiocfg</pre>."

#: src/modules/initramfscfg/main.py:32
msgid "Configuring initramfs."
msgstr "A configurar o initramfs."

#: src/modules/localecfg/main.py:31
msgid "Configuring locales."
msgstr "A configurar a localização."

#: src/modules/mkinitfs/main.py:27
msgid "Creating initramfs with mkinitfs."
msgstr "A criar o initramfs com o mkinitfs."

#: src/modules/mkinitfs/main.py:49
msgid "Failed to run mkinitfs on the target"
msgstr "Falha ao executar o mkintfs no destino"

#: src/modules/mkinitfs/main.py:50
msgid "The exit code was {}"
msgstr "O código de saída foi {}"

#: src/modules/mount/main.py:43
msgid "Mounting partitions."
msgstr "A montar partições."

#: src/modules/mount/main.py:164 src/modules/mount/main.py:200
msgid "Internal error mounting zfs datasets"
msgstr "Erro interno ao montar os conjuntos de dados zfs"

#: src/modules/mount/main.py:176
msgid "Failed to import zpool"
msgstr "Falha ao importar zpool"

#: src/modules/mount/main.py:192
msgid "Failed to unlock zpool"
msgstr "Falha ao desbloquear zpool"

#: src/modules/mount/main.py:209 src/modules/mount/main.py:214
msgid "Failed to set zfs mountpoint"
msgstr "Falha ao definir o ponto de montagem zfs"

#: src/modules/mount/main.py:365
msgid "zfs mounting error"
msgstr "erro de montagem zfs"

#: src/modules/networkcfg/main.py:29
msgid "Saving network configuration."
msgstr "A guardar a configuração de rede."

#: src/modules/openrcdmcryptcfg/main.py:26
msgid "Configuring OpenRC dmcrypt service."
msgstr "A configurar o serviço OpenRC dmcrypt."

#: src/modules/packages/main.py:54 src/modules/packages/main.py:65
#: src/modules/packages/main.py:75
msgid "Install packages."
msgstr "Instalar pacotes."

#: src/modules/packages/main.py:63
#, python-format
msgid "Processing packages (%(count)d / %(total)d)"
msgstr "A processar pacotes (%(count)d / %(total)d)"

#: src/modules/packages/main.py:68
#, python-format
msgid "Installing one package."
msgid_plural "Installing %(num)d packages."
msgstr[0] "A instalar um pacote."
msgstr[1] "A instalar %(num)d pacotes."
msgstr[2] "A instalar %(num)d pacotes."

#: src/modules/packages/main.py:71
#, python-format
msgid "Removing one package."
msgid_plural "Removing %(num)d packages."
msgstr[0] "A remover um pacote."
msgstr[1] "A remover %(num)d pacotes."
msgstr[2] "A remover %(num)d pacotes."

#: src/modules/packages/main.py:740 src/modules/packages/main.py:752
#: src/modules/packages/main.py:780
msgid "Package Manager error"
msgstr "Erro do gestor de pacotes"

#: src/modules/packages/main.py:741
msgid ""
"The package manager could not prepare updates. The command <pre>{!s}</pre> "
"returned error code {!s}."
msgstr ""
"O gestor de pacotes não conseguiu preparar atualizações. O comando "
"<pre>{!s}</pre> apresentou o código de erro {!s}."

#: src/modules/packages/main.py:753
msgid ""
"The package manager could not update the system. The command <pre>{!s}</pre>"
" returned error code {!s}."
msgstr ""
"O gestor de pacotes não conseguiu atualizar o sistema. O comando "
"<pre>{!s}</pre> apresentou o código de erro {!s}."

#: src/modules/packages/main.py:781
msgid ""
"The package manager could not make changes to the installed system. The "
"command <pre>{!s}</pre> returned error code {!s}."
msgstr ""
"O gestor de pacotes não pôde fazer alterações ao sistema instalado. O "
"comando <pre>{!s}</pre>devolveu o código de erro {!s}."

#: src/modules/plymouthcfg/main.py:27
msgid "Configure Plymouth theme"
msgstr "Configurar tema do Plymouth"

#: src/modules/rawfs/main.py:26
msgid "Installing data."
msgstr "A instalar dados."

#: src/modules/services-openrc/main.py:29
msgid "Configure OpenRC services"
msgstr "Configurar serviços OpenRC"

#: src/modules/services-openrc/main.py:57
msgid "Cannot add service {name!s} to run-level {level!s}."
msgstr ""
"Não é possível adicionar o serviço {name!s} ao nível de execução {level!s}."

#: src/modules/services-openrc/main.py:59
msgid "Cannot remove service {name!s} from run-level {level!s}."
msgstr ""
"Não é possível remover o serviço {name!s} do nível de execução {level!s}."

#: src/modules/services-openrc/main.py:61
msgid ""
"Unknown service-action <code>{arg!s}</code> for service {name!s} in run-"
"level {level!s}."
msgstr ""
"Serviço de ação desconhecido <code>{arg!s}</code> para serviço {name!s} em "
"nível de execução {level!s}."

#: src/modules/services-openrc/main.py:93
msgid "Cannot modify service"
msgstr "Não é possível modificar serviço"

#: src/modules/services-openrc/main.py:94
msgid ""
"<code>rc-update {arg!s}</code> call in chroot returned error code {num!s}."
msgstr ""
"<code>rc-update {arg!s}</code> chamar pelo chroot retornou com código de "
"erro {num!s}."

#: src/modules/services-openrc/main.py:101
msgid "Target runlevel does not exist"
msgstr "O nível de execução do destino não existe"

#: src/modules/services-openrc/main.py:102
msgid ""
"The path for runlevel {level!s} is <code>{path!s}</code>, which does not "
"exist."
msgstr ""
"O caminho para o nível de execução {level!s} é <code>{path!s}</code>, que "
"não existe."

#: src/modules/services-openrc/main.py:110
msgid "Target service does not exist"
msgstr "O serviço do destino não existe"

#: src/modules/services-openrc/main.py:111
msgid ""
"The path for service {name!s} is <code>{path!s}</code>, which does not "
"exist."
msgstr ""
"O caminho para o serviço {name!s} é <code>{path!s}</code>, que não existe."

#: src/modules/services-systemd/main.py:26
msgid "Configure systemd units"
msgstr "Configurar unidades systemd"

#: src/modules/services-systemd/main.py:64
msgid "Cannot modify unit"
msgstr "Não é possível modificar unidade"

#: src/modules/services-systemd/main.py:65
msgid ""
"<code>systemctl {_action!s}</code> call in chroot returned error code "
"{_exit_code!s}."
msgstr ""
"<code>systemctl {_action!s}</code> chamar pelo chroot retornou com código de"
" erro {_exit_code!s}."

#: src/modules/services-systemd/main.py:66
msgid "Cannot {_action!s} systemd unit <code>{_name!s}</code>."
msgstr "Não é possível {_action!s} unidade systemd <code>{_name!s}</code>."

#: src/modules/unpackfs/main.py:34
msgid "Filling up filesystems."
msgstr "A preencher os sistemas de ficheiros."

#: src/modules/unpackfs/main.py:254
msgid "rsync failed with error code {}."
msgstr "rsync falhou com código de erro {}."

#: src/modules/unpackfs/main.py:299
msgid "Unpacking image {}/{}, file {}/{}"
msgstr "A descompactar imagem {}/{}, ficheiro {}/{}"

#: src/modules/unpackfs/main.py:314
msgid "Starting to unpack {}"
msgstr "A começar a descompactação {}"

#: src/modules/unpackfs/main.py:323 src/modules/unpackfs/main.py:467
msgid "Failed to unpack image \"{}\""
msgstr "Falha ao descompactar imagem \"{}\""

#: src/modules/unpackfs/main.py:430
msgid "No mount point for root partition"
msgstr "Nenhum ponto de montagem para a partição root"

#: src/modules/unpackfs/main.py:431
msgid "globalstorage does not contain a \"rootMountPoint\" key."
msgstr "o armazenamento global não contém uma chave \"rootMountPoint\"."

#: src/modules/unpackfs/main.py:434
msgid "Bad mount point for root partition"
msgstr "Ponto de montagem mau para partição root"

#: src/modules/unpackfs/main.py:435
msgid "rootMountPoint is \"{}\", which does not exist."
msgstr "rootMountPoint é \"{}\", que não existe."

#: src/modules/unpackfs/main.py:439 src/modules/unpackfs/main.py:455
#: src/modules/unpackfs/main.py:459 src/modules/unpackfs/main.py:465
#: src/modules/unpackfs/main.py:480
msgid "Bad unpackfs configuration"
msgstr "Má configuração do unpackfs"

#: src/modules/unpackfs/main.py:440
msgid "There is no configuration information."
msgstr "Não há informação de configuração."

#: src/modules/unpackfs/main.py:456
msgid "The filesystem for \"{}\" ({}) is not supported by your current kernel"
msgstr ""
"O sistema de ficheiros para \"{}\" ({}) não é suportado pelo seu kernel "
"atual"

#: src/modules/unpackfs/main.py:460
msgid "The source filesystem \"{}\" does not exist"
msgstr "O sistema de ficheiros fonte \"{}\" não existe"

#: src/modules/unpackfs/main.py:466
msgid ""
"Failed to find unsquashfs, make sure you have the squashfs-tools package "
"installed."
msgstr ""
"Falha ao localizar o unsquashfs, certifique-se de que tem o pacote squashfs-"
"tools instalado."

#: src/modules/unpackfs/main.py:481
msgid "The destination \"{}\" in the target system is not a directory"
msgstr "O destino \"{}\" no sistema de destino não é um diretório"

#: src/modules/zfshostid/main.py:27
msgid "Copying zfs generated hostid."
msgstr "A copiar o hostid gerado pelo zfs."
